export const brand = "Relay";
export const localeNames = {ja:"日本語",en:"English"} as const;
export const ja = {
  app:'Relay · 案件ワークスペース', workspace:'チームワークスペース', today:'今日の対応', cases:'案件一覧', reviews:'更新案の確認', imports:'情報の取込', system:'デザインと構成',
  tagline:'会話から、次の行動へ。', demo:'デザインプレビュー', demoNote:'架空データ · 外部接続なし', member:'管理者', memberRole:'チーム全体を表示', language:'表示言語', menu:'メニュー', skip:'本文へ移動',
  todayTitle:'次の一歩を、明確に。', todaySub:'今日進める仕事と、その判断に必要な情報をまとめました。', add:'情報を取り込む',
  dueToday:'今日までの対応', overdue:'対応期限を超過', unassigned:'担当・期限の確認', unit:'件', priority:'優先する仕事', asOf:'情報基準：2026年9月11日 10:30',
  todayHint:'今、担当者の対応が必要', overdueHint:'完了した場合は記録を追加', unassignedHint:'次の動きを決めましょう', sourceHint:'取得済みの会話と担当者の記録を表示しています。電話で完了した仕事は、結果を記録してください。',
  assistant:'アシスタントから', assistantTitle:'了承のあとにも、次の仕事。', assistantBody:'お客様の日程了承を確認しました。工事会社への確定連絡を、次の対応として残します。', reviewOpen:'更新案を確認する',
  handoffTitle:'経緯を、ひとつにつなぐ。', handoffBody:'案件を開くだけで、次の担当者へ渡す情報がまとまります。', browse:'案件を見る',
  open:'詳細を開く', owner:'社内担当', waiting:'待っている相手', due:'対応期限', stage:'進行段階', next:'次の予定', status:'状態', name:'お客様', action:'次の対応',
  casesTitle:'案件一覧', casesSub:'担当者、期限、次の対応。案件を進める情報を一か所で。', search:'顧客名・エリア・対応内容で検索', allOwners:'すべての担当者', all:'すべて', needsAttention:'今日までの対応', unknown:'担当未設定', count:'{count}件の案件',
  noResults:'条件に合う案件がありません', noResultsSub:'検索する言葉や担当者を変更してください。', resetFilters:'条件を解除する',
  todo:'未着手', doing:'対応中', awaiting:'相手待ち', done:'完了', dueNow:'本日 17:00', dueDay:'本日中', dueUnknown:'未設定', overdueDate:'9月10日', futureDate:'9月14日', none:'—',
  stageSchedule:'商談調整', stageContract:'契約後対応', stageInstall:'工事調整', back:'案件一覧へ戻る', detailSub:'最新の状況、経緯、次の対応を確認できます。', summary:'いま必要な対応', timeline:'これまでの経緯', evidence:'判断の根拠', evidenceOrigin:'業務LINE · 日本語の架空の会話',
  record:'対応結果を記録', recordSub:'電話などで進んだ仕事も、短いメモで残せます。', recordLabel:'対応内容・相手の回答', recordPlaceholder:'例：お客様に電話。候補日で了承。工事会社への連絡はこれから。', save:'メモを保存', complete:'このタスクを完了', completed:'タスク完了済み', reportHint:'メモの保存だけでは、予定やタスクの状態は変わりません。', reportError:'具体的な対応結果を5文字以上で入力してください。', reportSaved:'対応メモを保存しました。', taskCompleted:'担当者の報告に基づき、このタスクを完了しました。', reported:'本人による報告', reports:'担当者の記録',
  handoff:'引き継ぎを作成', handoffHeading:'引き継ぎメモ', close:'閉じる', copy:'コピーする', copied:'コピーしました。外部への送信はしていません。', copyError:'自動コピーできません。表示文を選択してコピーしてください。', noReport:'対応記録なし', handoffCaution:'この文は取得済みの架空データに基づくプレビューです。',
  reviewTitle:'会話を、次の対応へ。', reviewSub:'変更内容と元の発言を見て、案件に反映します。', proposal:'新しい会話から作成', proposalHeading:'顧客A様の現調日について', before:'これまで', after:'反映する内容', beforeText:'お客様へ現調候補日を確認', afterText:'工事会社へ現調日の確定連絡', customerAgreed:'お客様は了承済み', customerPending:'お客様へ確認中', reviewCaution:'工事会社からの了承が確認できるまで、現調日は「候補」のままです。', approve:'この内容で反映', reject:'却下する', reviewOwnerHint:'次の担当者と期限は、この画面で確認してから反映します。', reviewComplete:'更新案を反映しました', reviewRejected:'更新案を却下しました', reviewEmpty:'確認待ちの更新案はありません。', reviewNoSend:'画面内の更新のみを体験できます。工事会社への連絡は送信しません。', showEvidence:'元の発言を開く', reviewConflict:'先に担当者の記録が更新されています。再読込でサンプルを初期化して、更新案を確認してください。',
  importTitle:'会話を取り込む。仕事がつながる。', importSub:'一度入力した情報を、もう一度入力しなくて済むように。', history:'LINEの書き出し履歴', dropTitle:'業務のやり取りを、案件の記憶に。', dropSub:'本番ではTXTと会話グループを指定します。ここではサンプルの取込結果を確認できます。', sample:'サンプル結果を見る', sampleShown:'サンプル結果を表示中', imported:'サンプルの取込結果', file:'履歴ファイル', period:'基準日', duplicates:'重複した投稿', newMessages:'新しい投稿', two:'2件を除外', one:'1件 → 更新案を作成', importNote:'ファイルのアップロードやAI解析は行っていません。', step1:'履歴を受け取る', step2:'重複と機密情報を整理', step3:'案件へひも付ける', step4:'根拠付きで確認する', historyNote:'過去の履歴は当時の状態を再現し、現在も動いている案件を確認してから運用を開始します。',
  systemTitle:'静かな見た目。明確な仕組み。', systemSub:'デザインの共通ルールと、これからの開発構成。', overdueDeadline:'期限超過 · {date}', mainColor:'メイン · 墨黒', subColor:'サブ · 白', accentColor:'アクセント · 青', mainColorUse:'本文、見出し、選択状態。仕事の情報を明確に。', subColorUse:'読む面と入力面。余白で情報の関係を整理。', accentColorUse:'主要ボタンとフォーカス。操作の行き先を明確に。', derivedColors:'グレーは墨黒と白の混色のみ。青の濃淡は操作時にだけ使い、独立した状態色は増やしません。', typeTitle:'文字の階層', pageType:'画面タイトル', sectionType:'領域見出し', bodyType:'本文・入力', labelType:'ラベル', typeSample:'次の仕事を、明確に。', tokenSize:'{size}px', typeFootnote:'本文の行高は{leading}。狭幅の画面タイトルは{mobile}。見出しにも日本語の自然な字間を保ちます。', spaceTitle:'情報の距離と形', relatedGap:'関連する要素', groupGap:'同じグループ', sectionGap:'独立した領域', shapeSpecs:'角丸はメディア・入力 {media}、カード {card}、補助パネル {panel}。ボタンはピル型で高さ {action}、操作領域は {touch} 以上。', statusTreatment:'状態は文字、アイコン、線種で識別します。判断根拠を小さな補足へ押し込めません。', palette:'役割で統一したデザイン', paletteBody:'メインは墨黒、サブは白、アクセントは青。情報を読む面は白、文字と構造は墨黒、次へ進む主要操作は青で揃えます。', platform:'本番スタックの推奨案', platformBody:'TypeScript・React・Next.js・Tailwind CSS・shadcn/ui。認証とファイル保存も含め、Supabaseを第一候補とします。', sequencing:'効率のよい実装順序', sequencingBody:'デザイン仕様 → 新スタックの基盤 → 共通部品 → 全画面 → DBとAIの接続。今回の画面はデザイン検討用です。', reusable:'移行時に引き継ぐもの', reusableBody:'型付きのトークン、翻訳キー、案件の型、画面の構成を分離しています。DOMを描画するコードはReactで置き換えます。', guide:'デザインガイド', architecture:'スタックの比較と提案',
  emptyToday:'今日までの対応は完了しました', emptyTodaySub:'案件一覧から、次の予定を確認できます。', previewFooter:'プレビューの操作はメモリー内のみです。再読込で初期状態に戻ります。',
} as const;
export type MessageKey = keyof typeof ja;
export type Locale = 'ja' | 'en';
export const en: Record<MessageKey,string> = {
  app:'Relay · Case workspace', workspace:'Team workspace', today:'Today', cases:'Cases', reviews:'Review updates', imports:'Import conversations', system:'Design & architecture', tagline:'From conversation to action.', demo:'Design preview', demoNote:'Sample data · No connections', member:'Administrator', memberRole:'Viewing the whole team', language:'Display language', menu:'Menu', skip:'Skip to content',
  todayTitle:'Make the next step clear.', todaySub:'The work to move forward today, with the context to make a decision.', add:'Import information', dueToday:'Due by today', overdue:'Past due', unassigned:'Owner or date needed', unit:'', priority:'Start with these tasks', asOf:'Information as of Sep 11, 2026, 10:30 JST', todayHint:'Ready for your attention', overdueHint:'Add a report if already completed', unassignedHint:'Decide who acts next', sourceHint:'Based on imported conversations and team reports. Add a note for work completed by phone.', assistant:'From your assistant', assistantTitle:'An agreement is another beginning.', assistantBody:'The customer agreed to the proposed date. Confirming it with the installation team remains a separate task.', reviewOpen:'Review the update', handoffTitle:'Keep the whole story together.', handoffBody:'Open a case to prepare the context for the next person.', browse:'Explore cases', open:'Open details', owner:'Internal owner', waiting:'Waiting for', due:'Response deadline', stage:'Case stage', next:'Next appointment', status:'Status', name:'Customer', action:'Next action',
  casesTitle:'All cases', casesSub:'Owners, deadlines, and next actions. The context to keep work moving.', search:'Search customers, areas, or actions', allOwners:'All owners', all:'All', needsAttention:'Due by today', unknown:'Unassigned', count:'{count} cases', noResults:'No cases match your filters', noResultsSub:'Try a different search or owner.', resetFilters:'Clear filters', todo:'To do', doing:'In progress', awaiting:'Waiting', done:'Completed', dueNow:'Today, 17:00', dueDay:'Today', dueUnknown:'Not set', overdueDate:'September 10', futureDate:'September 14', none:'—', stageSchedule:'Meeting scheduling', stageContract:'Post-contract', stageInstall:'Installation scheduling', back:'Back to cases', detailSub:'Review the current status, history, and next action.', summary:'What needs to happen next', timeline:'The story so far', evidence:'Supporting evidence', evidenceOrigin:'Work chat · Fictional Japanese conversation', record:'Record an outcome', recordSub:'A short note keeps work done by phone in the loop.', recordLabel:'Your action and the response', recordPlaceholder:'For example: Called the customer. They agreed. The installation team still needs confirmation.', save:'Save note', complete:'Complete this task', completed:'Task completed', reportHint:'Saving a note does not change appointment or task status.', reportError:'Describe the outcome in at least five characters.', reportSaved:'Your note has been saved.', taskCompleted:'This task was completed based on your report.', reported:'Self-reported outcome', reports:'Team reports', handoff:'Prepare handoff', handoffHeading:'Handoff note', close:'Close', copy:'Copy text', copied:'Copied. Nothing was sent externally.', copyError:'Automatic copy failed. Select and copy the displayed text.', noReport:'No report recorded', handoffCaution:'This preview is based on available fictional records.',
  reviewTitle:'Turn conversation into progress.', reviewSub:'Compare the proposed change with its source before applying it.', proposal:'From a new conversation', proposalHeading:'Customer A · Site visit', before:'Previously', after:'Proposed change', beforeText:'Confirm the proposed visit date with the customer', afterText:'Confirm the visit date with the installation team', customerAgreed:'Customer agreed', customerPending:'Customer confirmation pending', reviewCaution:'The visit remains tentative until the installation team also agrees.', approve:'Apply this update', reject:'Reject update', reviewOwnerHint:'Review the next owner and deadline before applying the update.', reviewComplete:'The update has been applied', reviewRejected:'The update has been rejected', reviewEmpty:'No updates are waiting for review.', reviewNoSend:'This changes the preview only. No message is sent to the installation team.', showEvidence:'Open original message', reviewConflict:'A team report has changed this case. Reload to reset the sample before reviewing this update.',
  importTitle:'Bring conversations into focus.', importSub:'Use information already shared, without entering it again.', history:'Exported LINE conversation', dropTitle:'Give every case a memory.', dropSub:'The production app will accept a TXT file and a conversation group. Explore a sample import result here.', sample:'View sample result', sampleShown:'Showing sample result', imported:'Sample import result', file:'History file', period:'Reference date', duplicates:'Duplicate messages', newMessages:'New messages', two:'2 excluded', one:'1 message → update proposal', importNote:'No file has been uploaded and no AI processing has run.', step1:'Receive history', step2:'Handle duplicates and secrets', step3:'Link to the right case', step4:'Review with evidence', historyNote:'Historical imports reconstruct the past first. Activate only cases confirmed to be currently in progress.',
  systemTitle:'Quiet design. Clear decisions.', systemSub:'Shared design principles and the proposed development stack.', overdueDeadline:'Past due · {date}', mainColor:'Main · Near-black', subColor:'Supporting · White', accentColor:'Accent · Blue', mainColorUse:'Content, headings, and selection. A clear structure for work.', subColorUse:'Reading and input surfaces. Space defines relationships.', accentColorUse:'Primary actions and keyboard focus. A clear next step.', derivedColors:'Grays blend near-black and white. Blue shades are reserved for interaction. Statuses introduce no additional colors.', typeTitle:'Type hierarchy', pageType:'Page title', sectionType:'Section title', bodyType:'Body and input', labelType:'Label', typeSample:'Make the next step clear.', tokenSize:'{size}px', typeFootnote:'Body line height is {leading}. Page titles use {mobile} on narrow screens. Headings retain natural letter spacing.', spaceTitle:'Space and shape', relatedGap:'Related elements', groupGap:'Within a group', sectionGap:'Between sections', shapeSpecs:'Corner radii: media and inputs {media}, cards {card}, supporting panels {panel}. Pill buttons are {action} high; touch targets are at least {touch}.', statusTreatment:'Labels, icons, and line styles identify states. Decision-making context remains full-size body text.', palette:'Design organized by role', paletteBody:'Near-black is the main color, white is the supporting color, and blue is the accent. White holds the content; near-black defines its structure; blue highlights the primary action.', platform:'Recommended production stack', platformBody:'TypeScript, React, Next.js, Tailwind CSS, and shadcn/ui. Supabase is the first choice for database, authentication, and file storage.', sequencing:'An efficient build sequence', sequencingBody:'Design specification → framework foundation → shared components → all screens → database and AI. This remains a design preview.', reusable:'Built to inform the next step', reusableBody:'Typed tokens, translation keys, case types, and page structure are separate. React will replace the DOM rendering code.', guide:'Design guidelines', architecture:'Stack comparison and recommendation', emptyToday:'All work due today is complete', emptyTodaySub:'Explore the remaining cases to prepare for the next appointments.', previewFooter:'Preview changes are kept in memory only. Reload to reset.',
};
export function translate(locale:Locale,key:MessageKey,params:Record<string,string|number>={}):string {
  const text:string=(locale==='en'?en:ja)[key];
  return text.replace(/\{(\w+)\}/g,(_,name:string)=>String(params[name]??`{${name}}`));
}
