import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {randomBytes,generateKeyPairSync,sign} from 'node:crypto';
import * as oidc from 'openid-client';
import {PGlite} from '@electric-sql/pglite';
import {Client,StreamableHTTPClientTransport} from '@modelcontextprotocol/client';
await mkdir('.vercel/check-calendar',{recursive:true});
await build({stdin:{contents:`export * from './src/scheduling/slots'; export * from './src/server/calendar'; export * from './src/server/vault'; export * from './src/server/mcp'; export * from './src/server/auth'; export {default as endpoint} from './src/server/handler';`,resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',packages:'external',outfile:'.vercel/check-calendar/calendar.mjs'});
const api=await import(pathToFileURL(process.cwd()+'/.vercel/check-calendar/calendar.mjs'));
const pg=new PGlite();
const wrap=client=>({query:async(text,values)=>(await client.query(text,values)).rows,transaction:work=>client.transaction(tx=>work(wrap(tx)))}),db=wrap(pg);
for(const file of ['001_identity_line.sql','002_calendar_mcp.sql'])await pg.exec(await readFile('migrations/'+file,'utf8'));
process.env.APP_ORIGIN='https://relay.test';process.env.ALLOWED_GOOGLE_EMAILS='owner@gmail.com,second@gmail.com';process.env.TOKEN_ENCRYPTION_KEY=randomBytes(32).toString('base64');
const owner={email:'owner@gmail.com',subject:'one'},second={email:'second@gmail.com',subject:'two'};
const now='2026-09-11T00:00:00Z';
const criteria=api.searchSchema.parse({fromDate:'2026-09-14',durationMinutes:60,limit:5});
const empty=api.findSlots(criteria,[],now);assert.equal(empty.length,5);assert.equal(empty[0].start,'2026-09-14T00:00:00Z');
const busy=[{start:'2026-09-14T00:30:00Z',end:'2026-09-14T02:00:00Z'}];
const buffered=api.findSlots(criteria,busy,now);assert.equal(buffered[0].start,'2026-09-14T02:15:00Z');
assert.equal(api.findSlots({...criteria,fromDate:'2026-09-12',days:2},[],now).length,0);
assert.equal(api.findSlots({...criteria,fromDate:'2026-09-11'},[],now)[0].start,'2026-09-11T00:30:00Z');
assert.throws(()=>api.findSlots({...criteria,timeZone:'Not/AZone'},[],now));
assert.throws(()=>api.findSlots({...criteria,fromDate:'2026-09-10'},[],now));
assert.throws(()=>api.findSlots(criteria,[{start:busy[0].end,end:busy[0].start}],now));
assert.throws(()=>api.searchSchema.parse({...criteria,days:99}));
assert.throws(()=>api.searchSchema.parse({...criteria,endHour:8}));
const dstSpring=api.findSlots({...criteria,fromDate:'2026-03-08',days:1,timeZone:'America/New_York',weekdays:[7],startHour:1,endHour:4,bufferMinutes:0,limit:10},[],'2026-03-07T00:00:00Z');
assert.equal(dstSpring[0].start,'2026-03-08T06:00:00Z');assert.equal(dstSpring.at(-1).end,'2026-03-08T08:00:00Z');
const cipher=api.seal('synthetic-refresh',owner.subject);assert.ok(!cipher.includes('synthetic-refresh'));assert.equal(api.unseal(cipher,owner.subject),'synthetic-refresh');assert.throws(()=>api.unseal(cipher,second.subject));assert.throws(()=>api.unseal(cipher.slice(0,-3)+'aaa',owner.subject));
await db.query('INSERT INTO relay_private.calendar_connections(owner_subject,refresh_cipher) VALUES($1,$2)',[owner.subject,cipher]);
assert.deepEqual(await api.calendarStatus(owner,db),{ready:true,connected:true});assert.equal((await api.calendarStatus(second,db)).connected,false);
const events=new Map();let externalBusy=[];let inserts=0;let timeoutAfterInsert=false;
const fake={busy:async()=>[...externalBusy,...[...events.values()].map(e=>({start:e.start.dateTime,end:e.end.dateTime}))],get:async id=>events.get(id)??null,insert:async event=>{inserts++;events.set(event.id,event);if(timeoutAfterInsert){timeoutAfterInsert=false;throw new Error('timeout')}return event;}};
const input={...criteria,title:'Synthetic meeting'};
const proposal=(await api.proposeSchedule(owner,input,db,fake,now)).proposals[0];
await assert.rejects(api.bookSlot(second,proposal.id,db,fake,now),e=>e.status===404);assert.equal(inserts,0);
externalBusy=[{start:proposal.start,end:proposal.end}];await assert.rejects(api.bookSlot(owner,proposal.id,db,fake,now),e=>e.code==='calendarConflict');assert.equal(inserts,0);externalBusy=[];
const booked=await api.bookSlot(owner,proposal.id,db,fake,now);assert.equal(booked.state,'booked');await api.bookSlot(owner,proposal.id,db,fake,now);assert.equal(inserts,1);
const stored=[...events.values()][0];assert.match(stored.id,/^[0-9a-v]{5,1024}$/);assert.equal(stored.attendees,undefined);
const uncertain=(await api.proposeSchedule(owner,input,db,fake,now)).proposals[0];timeoutAfterInsert=true;await assert.rejects(api.bookSlot(owner,uncertain.id,db,fake,now));await api.bookSlot(owner,uncertain.id,db,fake,now);assert.equal(inserts,2);
const expired=(await api.proposeSchedule(owner,input,db,fake,now)).proposals[0];await db.query("UPDATE relay_private.schedule_proposals SET expires_at='2026-01-01' WHERE id=$1",[expired.id]);await assert.rejects(api.bookSlot(owner,expired.id,db,fake,now),e=>e.code==='proposalExpired');
stored.summary='Externally edited';await assert.rejects(api.bookSlot(owner,proposal.id,db,fake,now),e=>e.code==='calendarChanged');
// Account-bound OAuth + encrypted refresh token persistence with real signed OIDC.
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});
const config=new oidc.Configuration({issuer:'https://accounts.google.com',authorization_endpoint:'https://accounts.google.com/o/oauth2/v2/auth',token_endpoint:'https://oauth.test/token',jwks_uri:'https://oauth.test/keys',id_token_signing_alg_values_supported:['RS256']},'test-client','test-secret');oidc.enableNonRepudiationChecks(config);
let nonce='',sub=owner.subject,scopes=api.calendarScopes.join(' ');
const base64=value=>Buffer.from(JSON.stringify(value)).toString('base64url');
config[oidc.customFetch]=async(url,options)=>{
 if(String(url).endsWith('/keys'))return Response.json({keys:[{...publicKey.export({format:'jwk'}),kid:'test',use:'sig',alg:'RS256'}]});
 const body=new URLSearchParams(options.body);
 if(body.get('grant_type')==='refresh_token'){assert.equal(body.get('refresh_token'),'new-synthetic-refresh');return Response.json({access_token:'synthetic-access',token_type:'Bearer'});}
 const timestamp=Math.floor(Date.now()/1000),data=base64({alg:'RS256',kid:'test'})+'.'+base64({iss:'https://accounts.google.com',aud:'test-client',sub,email:owner.email,email_verified:true,nonce,iat:timestamp,exp:timestamp+300});
 return Response.json({access_token:'synthetic-access',token_type:'Bearer',refresh_token:'new-synthetic-refresh',scope:scopes,id_token:data+'.'+sign('RSA-SHA256',Buffer.from(data),privateKey).toString('base64url')});
};
async function consent(){const response=await api.startCalendar(owner,db,config);const url=new URL(response.headers.get('location'));nonce=url.searchParams.get('nonce');assert.equal(url.searchParams.get('access_type'),'offline');assert.equal(url.searchParams.get('code_challenge_method'),'S256');const cookie=response.headers.get('set-cookie');return new Request('https://relay.test/api/calendar/callback?code=synthetic&state='+url.searchParams.get('state'),{headers:{cookie}});}
let callback=await consent();sub=second.subject;assert.match((await api.finishCalendar(callback,owner,db,config)).headers.get('location'),/failed/);
sub=owner.subject;scopes=api.calendarScopes[0];callback=await consent();assert.match((await api.finishCalendar(callback,owner,db,config)).headers.get('location'),/failed/);
scopes=api.calendarScopes.join(' ');callback=await consent();assert.match((await api.finishCalendar(callback,owner,db,config)).headers.get('location'),/connected/);assert.match((await api.finishCalendar(callback,owner,db,config)).headers.get('location'),/failed/);
assert.equal(api.unseal((await db.query('SELECT refresh_cipher FROM relay_private.calendar_connections WHERE owner_subject=$1',[owner.subject]))[0].refresh_cipher,owner.subject),'new-synthetic-refresh');
let captured;const google=await api.calendarClient(owner,db,config,async(url,options)=>{captured={url,options};return Response.json(JSON.parse(options.body));});await google.insert({id:'synthetic'});assert.ok(captured.url.endsWith('?sendUpdates=none'));const event=JSON.parse(captured.options.body);assert.equal(event.attendees,undefined);assert.equal(event.reminders.useDefault,false);assert.equal(event.visibility,'private');
const brokenGoogle=await api.calendarClient(owner,db,config,async()=>Response.json({calendars:{primary:{errors:[{reason:'forbidden'}]}}}));await assert.rejects(brokenGoogle.busy(now,now,'UTC'),e=>e.code==='calendarUnavailable');
// MCP tokens are revocable, expiring, hash-only and never accept Google tokens.
const readToken=await api.issueMcpToken(owner,'read',db);const mcpRequest=token=>new Request('https://relay.test/api/mcp',{method:'POST',headers:{Authorization:'Bearer '+token}});
assert.equal((await api.mcpIdentity(mcpRequest(readToken.token),db)).permission,'read');assert.equal(await api.mcpIdentity(mcpRequest('google-token'),db),null);
await assert.rejects(api.revokeMcpToken(second,readToken.id,db),e=>e.status===404);
process.env.ALLOWED_GOOGLE_EMAILS=second.email;assert.equal(await api.mcpIdentity(mcpRequest(readToken.token),db),null);process.env.ALLOWED_GOOGLE_EMAILS=owner.email+','+second.email;
await db.query("UPDATE relay_private.mcp_tokens SET expires_at=now()-interval '1 minute' WHERE id=$1",[readToken.id]);assert.equal(await api.mcpIdentity(mcpRequest(readToken.token),db),null);
const token=await api.issueMcpToken(owner,'book',db);await api.revokeMcpToken(owner,token.id,db);assert.equal(await api.mcpIdentity(mcpRequest(token.token),db),null);
// Real MCP Client over in-process HTTP transport; no socket or external service.
console.log('Calendar arithmetic, encryption, OIDC consent, booking recovery and token controls: OK.');
const readServer=api.schedulingMcp({...owner,permission:'read'},db,fake,now);
const client=new Client({name:'relay-test',version:'1.0.0'},{versionNegotiation:{mode:'auto'}});
await client.connect(new StreamableHTTPClientTransport(new URL('https://relay.test/api/mcp'),{fetch:(url,init)=>readServer.fetch(new Request(url,init))}));
const tools=await client.listTools();assert.deepEqual(tools.tools.map(t=>t.name).sort(),['relay_find_slots','relay_get_calendar_status']);
assert.equal((await client.callTool({name:'relay_get_calendar_status',arguments:{}})).structuredContent.connected,true);
const availability=await client.callTool({name:'relay_find_slots',arguments:criteria});assert.equal(availability.isError,undefined);assert.ok(availability.structuredContent.slots.length>0);
const invalid=await client.callTool({name:'relay_find_slots',arguments:{...criteria,days:100}});assert.equal(invalid.isError,true);
await assert.rejects(client.callTool({name:'relay_book_slot',arguments:{proposalId:proposal.id}}));
await client.close();await readServer.close();
const bookServer=api.schedulingMcp({...owner,permission:'book'},db,fake,now);
const writer=new Client({name:'relay-writer-test',version:'1.0.0'},{versionNegotiation:{mode:'auto'}});
await writer.connect(new StreamableHTTPClientTransport(new URL('https://relay.test/api/mcp'),{fetch:(url,init)=>bookServer.fetch(new Request(url,init))}));
assert.equal((await writer.listTools()).tools.length,4);
const prepared=await writer.callTool({name:'relay_propose_schedule',arguments:input});assert.ok(!prepared.isError);assert.equal(prepared.structuredContent.expiresIn,900);
const proposalId=prepared.structuredContent.proposals[0].id;
const booking=await writer.callTool({name:'relay_book_slot',arguments:{proposalId}});assert.ok(!booking.isError);assert.equal(booking.structuredContent.state,'booked');
const before=inserts;await writer.callTool({name:'relay_book_slot',arguments:{proposalId}});assert.equal(inserts,before);
const legacy=await bookServer.fetch(new Request('https://relay.test/api/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-11-25'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list',params:{}})}));
assert.equal(legacy.status,200);const legacyText=await legacy.text();const legacyValue=legacy.headers.get('content-type').includes('text/event-stream')?JSON.parse(legacyText.split('\n').find(line=>line.startsWith('data:')).slice(5)):JSON.parse(legacyText);assert.equal(legacyValue.result.tools.length,4);
await writer.close();await bookServer.close();
// HTTP facade validates bearer tokens and rejects foreign origins before tools.
const facadeToken=await api.issueMcpToken(owner,'read',db);
const raw=JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list',params:{}});
const req=new Request('https://relay.test/api/mcp',{method:'POST',headers:{Authorization:'Bearer '+facadeToken.token,'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-11-25'}});
const facade=await api.handleMcp(req,raw,db);assert.equal(facade.status,200);assert.ok((await facade.text()).includes('relay_find_slots'));
assert.equal((await api.handleMcp(new Request('https://relay.test/api/mcp',{method:'POST'}),raw,db)).status,401);
await assert.rejects(api.handleMcp(new Request('https://relay.test/api/mcp',{method:'POST',headers:{Origin:'https://evil.test'}}),raw,db),e=>e.status===403);
console.log('MCP SDK client: modern and legacy HTTP, tool schemas, read-only permissions, proposal/booking/retry and bearer facade: OK. No real events or invitations created.');
const evaluationServer=api.schedulingMcp({...owner,permission:'read'},db,{...fake,busy:async()=>busy},now);
const evaluator=new Client({name:'relay-evaluation',version:'1.0.0'},{versionNegotiation:{mode:'auto'}});
await evaluator.connect(new StreamableHTTPClientTransport(new URL('https://relay.test/api/mcp'),{fetch:(url,init)=>evaluationServer.fetch(new Request(url,init))}));
const evaluations=JSON.parse(await readFile('tests/evaluations/calendar.json','utf8'));
for(const sample of evaluations){
 assert.equal((await evaluator.callTool({name:'relay_get_calendar_status',arguments:{}})).structuredContent.connected,true);
 const {structuredContent}=await evaluator.callTool({name:'relay_find_slots',arguments:{...criteria,...sample.overrides}});
 const answer=sample.count?String(structuredContent.slots.length):(sample.last?structuredContent.slots.at(-1):structuredContent.slots[0]).start;
 assert.equal(answer,sample.answer,sample.question);
}
await evaluator.close();await evaluationServer.close();
console.log('Ten fixed scheduling evaluation answers verified through read-only MCP tools.');
await api.disconnectCalendar(owner,db);assert.equal((await api.calendarStatus(owner,db)).connected,false);
await pg.close();
