import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {build} from 'esbuild';
import {mkdir,readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {createHmac,randomUUID,generateKeyPairSync,sign} from 'node:crypto';
import * as oidc from 'openid-client';
import {PGlite} from '@electric-sql/pglite';
await mkdir('.vercel/check-auth',{recursive:true});
await build({stdin:{contents:`export * from './src/server/config'; export * from './src/server/access'; export * from './src/server/readiness'; export * from './src/server/auth'; export * from './src/server/admin'; export {handle} from './src/server/handler'; export * from './src/server/line'; export {default as endpoint,limitedBody} from './src/server/handler';`,resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',packages:'external',outfile:'.vercel/check-auth/server.mjs'});
const api=await import(pathToFileURL(process.cwd()+'/.vercel/check-auth/server.mjs'));
const pg=new PGlite();
const wrap=client=>({query:async(text,values)=>(await client.query(text,values)).rows,transaction:work=>client.transaction(tx=>work(wrap(tx)))});
const db=wrap(pg);
await pg.exec(await readFile('migrations/001_identity_line.sql','utf8'));
// Synthetic identities only; the production allowlist is never loaded here.
process.env.ALLOWED_GOOGLE_EMAILS='owner@gmail.com, second@gmail.com';
process.env.ADMIN_GOOGLE_EMAILS='owner@gmail.com';
process.env.APP_ORIGIN='https://relay.test';
process.env.GOOGLE_CLIENT_ID='synthetic-client';process.env.GOOGLE_CLIENT_SECRET='synthetic-secret';process.env.DATABASE_URL='postgres://unused:unused@localhost/unused';
process.env.LINE_CHANNEL_SECRET='synthetic-line-secret';
process.env.LINE_CHANNEL_ACCESS_TOKEN='synthetic-line-token';
const owner={email:'owner@gmail.com',subject:'subject-one'},second={email:'second@gmail.com',subject:'subject-two'};
assert.equal(api.allowed('Owner@gmail.com'),true);
for(const email of ['owner@gmail.com.evil','other@gmail.com','',null,{},['owner@gmail.com']])assert.equal(api.allowed(email),false);
assert.equal(api.allowed('owner@gmail.com',''),false);
assert.equal(api.sameOrigin(new Request('https://relay.test/api',{headers:{origin:'https://evil.test'}})),false);
assert.equal(api.sameOrigin(new Request('https://relay.test/api',{headers:{origin:'https://relay.test'}})),true);
for(const profile of [{email:owner.email,email_verified:false,sub:'1'},{email:'other@gmail.com',email_verified:true,sub:'1'},{email:owner.email,email_verified:'true',sub:'1'},{email:owner.email,email_verified:true}])assert.equal(api.verifiedIdentity(profile),null);
assert.deepEqual(api.verifiedIdentity({email:owner.email,email_verified:true,sub:owner.subject}),owner);
const token=api.randomToken();
const request=new Request('https://relay.test/api/session',{headers:{cookie:api.cookie(api.sessionCookie,token,28800)}});
await db.query("INSERT INTO relay_private.sessions VALUES($1,$2,$3,now()+interval '1 hour')",[api.hash(token),owner.subject,owner.email]);
assert.deepEqual(await api.session(request,db),owner);
assert.equal(await api.session(new Request('https://relay.test'),db),null);
assert.equal(await api.session(new Request('https://relay.test',{headers:{cookie:api.cookie(api.sessionCookie,api.randomToken(),28800)}}),db),null);
process.env.ALLOWED_GOOGLE_EMAILS=second.email;assert.equal(await api.session(request,db),null);process.env.ALLOWED_GOOGLE_EMAILS=owner.email+','+second.email;
await db.query("UPDATE relay_private.sessions SET expires_at=now()-interval '1 second'");assert.equal(await api.session(request,db),null);
await db.query("UPDATE relay_private.sessions SET expires_at=now()+interval '1 hour'");await api.logout(request,db);assert.equal(await api.session(request,db),null);
// Drive the actual OIDC library with a signed synthetic provider, with no network.
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});
const config=new oidc.Configuration({issuer:'https://accounts.google.com',authorization_endpoint:'https://accounts.google.com/o/oauth2/v2/auth',token_endpoint:'https://oauth.test/token',jwks_uri:'https://oauth.test/keys',id_token_signing_alg_values_supported:['RS256']},'test-client','test-secret');
oidc.enableNonRepudiationChecks(config);
let currentNonce='',claimOverride={},tamper=false,expectedVerifier='';
const base64=value=>Buffer.from(JSON.stringify(value)).toString('base64url');
config[oidc.customFetch]=async(url,options)=>{
 if(String(url)==='https://oauth.test/keys')return Response.json({keys:[{...publicKey.export({format:'jwk'}),kid:'test-key',use:'sig',alg:'RS256'}]});
 assert.equal(String(url),'https://oauth.test/token');
 assert.equal(new URLSearchParams(options.body).get('code_verifier'),expectedVerifier);
 const now=Math.floor(Date.now()/1000);
 const payload=base64({alg:'RS256',kid:'test-key'})+'.'+base64({iss:'https://accounts.google.com',aud:'test-client',sub:owner.subject,email:owner.email,email_verified:true,nonce:currentNonce,iat:now,exp:now+300,...claimOverride});
 const signature=sign('RSA-SHA256',Buffer.from(payload),privateKey).toString('base64url');
 return Response.json({access_token:'synthetic-access',token_type:'Bearer',id_token:payload+'.'+(tamper?'AAAA'+signature.slice(4):signature)});
};
async function callback(overrides={},badState=false,badSignature=false,destination='/',beforeFinish=()=>{},previousSession=''){
 claimOverride=overrides;tamper=badSignature;
 const start=await api.handle(new Request('https://relay.test/api/auth/start?route=start&lang=ar-EG&destination='+(destination==='/admin'?'admin':'untrusted')),db,config);
 assert.ok(start.headers.getSetCookie().some(value=>value.startsWith('relay-locale=ar-EG;')),'OAuth preserves the normalized language without JavaScript');
 const authorization=new URL(start.headers.get('location'));
 assert.equal(authorization.searchParams.get('code_challenge_method'),'S256');
 assert.equal(authorization.searchParams.get('scope'),'openid email');
 const browserCookie=start.headers.getSetCookie().find(value=>value.startsWith(api.oauthCookie+'=')).split(';')[0];
 const attempt=(await db.query('SELECT verifier FROM relay_private.oauth_attempts WHERE token_hash=$1',[api.hash(browserCookie.split('=')[1])]))[0];expectedVerifier=attempt.verifier;
 currentNonce=authorization.searchParams.get('nonce');
 const req=new Request('https://relay.test/api/auth/callback?route=callback&code=synthetic&state='+(badState?'wrong-state':authorization.searchParams.get('state')),{headers:{cookie:browserCookie+(previousSession?'; '+api.sessionCookie+'='+previousSession:'')}});
 await beforeFinish();
 return {result:await api.handle(req,db,config),req};
}
const success=await callback();assert.equal(success.result.headers.get('location'),'/');
const sessionHeader=success.result.headers.getSetCookie().find(value=>value.startsWith(api.sessionCookie+'='));
assert.ok(sessionHeader);assert.deepEqual(await api.session(new Request('https://relay.test',{headers:{cookie:sessionHeader}}),db),owner);
assert.equal((await api.finishLogin(success.req,db,config)).headers.get('location'),'/?auth=denied');
for(const overrides of [{email:'intruder@gmail.com'},{email_verified:false},{nonce:'wrong-nonce'},{aud:'different-client'},{iss:'https://evil.test'},{exp:1}])assert.equal((await callback(overrides)).result.headers.get('location'),'/?auth=denied');
assert.equal((await callback({},true)).result.headers.get('location'),'/?auth=denied');
assert.equal((await callback({},false,true)).result.headers.get('location'),'/?auth=denied');
const adminLogin=await callback({},false,false,'/admin');
assert.equal(adminLogin.result.headers.get('location'),'/admin');
const beforeDenied = await db.query('SELECT count(*)::int AS count FROM relay_private.sessions');
const memberAdminLogin = await callback({email:second.email,sub:second.subject},false,false,'/admin');
assert.equal(memberAdminLogin.result.headers.get('location'),'/admin?auth=denied');
assert.equal(memberAdminLogin.result.headers.getSetCookie().some(value=>value.startsWith(api.sessionCookie+'=')),false,'Rejected admin login must not issue a session');
assert.deepEqual(await db.query('SELECT count(*)::int AS count FROM relay_private.sessions'),beforeDenied);
assert.equal((await callback({email:second.email,sub:second.subject})).result.headers.get('location'),'/', 'Ordinary login still permits registered members');
const revokedAdminLogin=await callback({},false,false,'/admin',()=>{process.env.ADMIN_GOOGLE_EMAILS=second.email;});
assert.equal(revokedAdminLogin.result.headers.get('location'),'/admin?auth=denied','Admin permission is rechecked after Google consent');
assert.equal(revokedAdminLogin.result.headers.getSetCookie().some(value=>value.startsWith(api.sessionCookie+'=')),false);
process.env.ADMIN_GOOGLE_EMAILS='';
const attemptsBefore=await db.query('SELECT count(*)::int AS count FROM relay_private.oauth_attempts');
assert.equal((await api.startLogin(db,config,'/admin')).headers.get('location'),'/admin');
assert.deepEqual(await db.query('SELECT count(*)::int AS count FROM relay_private.oauth_attempts'),attemptsBefore,'Unset admin permissions do not start OAuth');
process.env.ADMIN_GOOGLE_EMAILS=owner.email;

assert.equal((await callback({email:'intruder@gmail.com'},false,false,'/admin')).result.headers.get('location'),'/admin?auth=denied');
assert.equal((await callback({},false,false,'https://evil.test')).result.headers.get('location'),'/', 'Only the fixed admin destination is accepted');
const noCallback=await api.finishLogin(new Request('https://relay.test/api/auth/callback?code=forged&state=forged'),db);assert.equal(noCallback.headers.get('location'),'/?auth=denied');
assert.match(noCallback.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);
assert.equal(api.validSignature('{}',null,process.env.LINE_CHANNEL_SECRET),false);
const signature=raw=>createHmac('sha256',process.env.LINE_CHANNEL_SECRET).update(raw).digest('base64');
assert.equal(api.validSignature('{}',signature('{}'),process.env.LINE_CHANNEL_SECRET),true);
assert.equal(api.validSignature('{ }',signature('{}'),process.env.LINE_CHANNEL_SECRET),false);
await assert.rejects(api.webhook('{"events":[]}',signature('{}'),db),e=>e.status===401);
await api.webhook('{"events":[]}',signature('{"events":[]}'),db);
await assert.rejects(api.issueCode(owner,'group',db),e=>e.code==='personalFirst');
const event=(code,kind='user',actor='U-personal',id=randomUUID())=>({webhookEventId:id,type:'message',source:{type:kind,userId:actor,...(kind==='group'?{groupId:'C-group'}:{})},message:{type:'text',text:code}});
const deliver=async(...events)=>{const raw=JSON.stringify({events});await api.webhook(raw,signature(raw),db)};
const code=await api.issueCode(owner,'user',db);
const link=event(code.code);
await deliver(link);let rows=await api.destinations(owner,db);assert.equal(rows.length,1);assert.equal(rows[0].enabled,false);
await deliver(link);assert.equal((await api.destinations(owner,db))[0].id,rows[0].id);
await deliver(event(code.code));assert.equal((await api.destinations(owner,db))[0].id,rows[0].id,'Consumed code must not create a new link');
await assert.rejects(api.changeDestination(second,rows[0].id,'confirm',db),e=>e.status===404);
await api.changeDestination(owner,rows[0].id,'confirm',db);
const groupCode=await api.issueCode(owner,'group',db);
await deliver(event(groupCode.code,'group','U-attacker'));assert.equal((await api.destinations(owner,db)).length,1);
await deliver(event(groupCode.code,'group'));rows=await api.destinations(owner,db);assert.equal(rows.length,2);
const group=rows.find(row=>row.kind==='group');
await api.changeDestination(owner,group.id,'confirm',db);
const personal=rows.find(row=>row.kind==='user');
let sends=0;
const sentRequests=[];
const sender=async(url,options)=>{sends++;sentRequests.push({url,options});return new Response('{}',{status:200})};
const notification={id:randomUUID(),destinationId:group.id,locale:'ja'};
await assert.rejects(api.notify(second,notification,db,sender),e=>e.status===404);assert.equal(sends,0);
await api.notify(owner,notification,db,sender);await api.notify(owner,notification,db,sender);assert.equal(sends,1);
assert.equal(sentRequests[0].url,'https://api.line.me/v2/bot/message/push');assert.equal(sentRequests[0].options.headers['X-Line-Retry-Key'],notification.id);
assert.equal(JSON.parse(sentRequests[0].options.body).to,'C-group');
await assert.rejects(api.notify(owner,{...notification,destinationId:personal.id},db,sender),e=>e.code==='conflict');
const retry={...notification,id:randomUUID()};
await assert.rejects(api.notify(owner,retry,db,async()=>{throw new Error('timeout')}),e=>e.code==='delivery');
const accepted=async(_url,options)=>{assert.equal(options.headers['X-Line-Retry-Key'],retry.id);return new Response('{}',{status:409,headers:{'x-line-accepted-request-id':'accepted'}})};
await api.notify(owner,retry,db,accepted);assert.equal((await db.query('SELECT state FROM relay_private.notifications WHERE id=$1',[retry.id]))[0].state,'sent');
const bad={...notification,id:randomUUID()};await assert.rejects(api.notify(owner,bad,db,async()=>new Response('{}',{status:400})),e=>e.code==='delivery');
await assert.rejects(api.notify(owner,bad,db,sender),e=>e.code==='pending');
for(let i=0;i<7;i++)await api.notify(owner,{...notification,id:randomUUID()},db,sender);
await assert.rejects(api.notify(owner,{...notification,id:randomUUID()},db,sender),e=>e.code==='rateLimit');
await deliver({webhookEventId:randomUUID(),type:'leave',source:{type:'group',groupId:'C-group'}});
await assert.rejects(api.changeDestination(owner,group.id,'confirm',db),e=>e.status===404);
await api.changeDestination(owner,personal.id,'remove',db);assert.equal((await api.destinations(owner,db)).length,0);
const expiring=await api.issueCode(owner,'user',db);await db.query("UPDATE relay_private.line_codes SET expires_at=now()-interval '1 minute'");await deliver(event(expiring.code));assert.equal((await api.destinations(owner,db)).length,0);
const revoked=await api.issueCode(owner,'user',db);process.env.ALLOWED_GOOGLE_EMAILS=second.email;await deliver(event(revoked.code));assert.equal((await api.destinations(owner,db)).length,0);
// Admin routes require both a current Google session and a separate admin allowlist.
process.env.ALLOWED_GOOGLE_EMAILS='owner@gmail.com,second@gmail.com,never@gmail.com,OWNER@gmail.com';
process.env.ADMIN_GOOGLE_EMAILS=' Owner@gmail.com, outsider@gmail.com ';
assert.equal(api.isAdmin(owner.email),false,'Inconsistent admin configuration fails closed');
assert.deepEqual(api.administratorIssues(),[{field:'ADMIN_GOOGLE_EMAILS',code:'adminNotAllowed'}]);
process.env.ADMIN_GOOGLE_EMAILS=' Owner@gmail.com ';
assert.equal(api.isAdmin(owner.email),true);
assert.equal(api.isAdmin(second.email),false);
assert.equal(api.isAdmin('outsider@gmail.com'),false);
for (const value of ['',undefined,{},['owner@gmail.com'],'owner@gmail.com.evil']) assert.equal(api.isAdmin(value),false);
const adminToken=api.randomToken(), memberToken=api.randomToken();
await db.query("INSERT INTO relay_private.sessions VALUES($1,$2,$3,now()+interval '1 hour')",[api.hash(adminToken),owner.subject,owner.email]);
await db.query("INSERT INTO relay_private.sessions VALUES($1,$2,$3,now()+interval '1 hour')",[api.hash(memberToken),second.subject,second.email]);
const adminRequest=(route,token='',method='GET',host='https://relay.test')=>new Request(host+'/api/relay?route='+route,{method,headers:{cookie:api.cookie(api.sessionCookie,token,28800),'x-admin':'true'}});
await assert.rejects(api.adminOverview(adminRequest('admin-overview'),db),e=>e.status===401);
await assert.rejects(api.adminOverview(adminRequest('admin-overview',memberToken),db),e=>e.status===403);
const overview=await api.adminOverview(adminRequest('admin-overview',adminToken),db);
assert.equal(overview.accounts.length,3,'Deduplicate account settings without adding unknown sessions');
assert.equal(overview.accounts.find(a=>a.email==='never@gmail.com').sessions,0);
assert.equal(overview.accounts.find(a=>a.email===owner.email).role,'admin');
assert.equal(overview.accounts.find(a=>a.email===second.email).role,'member');
assert.ok(overview.accounts.find(a=>a.email===owner.email).sessions>0);
assert.ok(!JSON.stringify(overview).includes(api.hash(adminToken)));
assert.ok(!JSON.stringify(overview).includes(process.env.LINE_CHANNEL_SECRET));
process.env.GOOGLE_CLIENT_ID='synthetic-client';process.env.GOOGLE_CLIENT_SECRET='synthetic-secret';process.env.DATABASE_URL='postgres://unused:unused@localhost/unused';
for (const route of ['admin-page','admin-overview']) {
 const denied=await api.handle(adminRequest(route,memberToken),db);
 assert.equal(denied.status,403);
 assert.ok(!(await denied.text()).includes('never@gmail.com'));
 assert.equal((await api.handle(adminRequest(route,adminToken,'POST'),db)).status,405);
}
const adminHtml=await api.handle(adminRequest('admin-page',adminToken),db);
assert.equal(adminHtml.status,200);assert.ok((await adminHtml.text()).includes('data-admin="true"'));
const loginAdmin=await api.handle(adminRequest('admin-page'),db);
assert.equal(loginAdmin.status,200);const adminLoginHtml=await loginAdmin.text();
assert.match(adminLoginHtml, /href="\/api\/auth\/start\?lang=ja&amp;destination=admin"/);
assert.ok(!adminLoginHtml.includes('disabled'));
assert.ok(adminLoginHtml.includes('aria-describedby="login-status"'));
assert.ok(adminLoginHtml.includes('action="/admin"'),'Language forms retain the admin entry');
assert.ok(!adminLoginHtml.includes('never@gmail.com'));
assert.equal((await api.handle(adminRequest('admin-overview'),db)).status,401);
assert.equal((await api.handle(adminRequest('admin-overview',adminToken),db)).status,200);
assert.equal((await api.handle(adminRequest('admin-overview',adminToken,'GET','https://old.test'),db)).status,403);
process.env.ADMIN_GOOGLE_EMAILS='';
const unconfiguredAdminPage=await api.handle(adminRequest('admin-page'),db);
const unconfiguredAdminHtml=await unconfiguredAdminPage.text();
assert.equal(unconfiguredAdminPage.status,503);
assert.ok(!unconfiguredAdminHtml.includes('/api/auth/start?'));
assert.ok(unconfiguredAdminHtml.includes('href="/admin?lang=ja"'),'Setup state offers a real refresh, not a disabled login button');
assert.ok(!unconfiguredAdminHtml.includes('assets/app.js'));
assert.equal((await api.handle(adminRequest('admin-overview',adminToken),db)).status,403,'Existing sessions lose admin privileges immediately');
process.env.ADMIN_GOOGLE_EMAILS=owner.email;
process.env.ALLOWED_GOOGLE_EMAILS=second.email;
assert.equal((await api.handle(adminRequest('admin-overview',adminToken),db)).status,401,'Admin allowlist cannot bypass ordinary access revocation');
process.env.ALLOWED_GOOGLE_EMAILS=owner.email+','+second.email;
await db.query("UPDATE relay_private.sessions SET expires_at=now()-interval '1 second' WHERE token_hash=$1",[api.hash(adminToken)]);
assert.equal((await api.handle(adminRequest('admin-overview',adminToken),db)).status,401);
// HTML navigation recovers from provider/DB outages without exposing their error values.
const unavailableDb={query:async()=>{throw new Error('postgres://private-secret@private-host/account');}};
const publicDuringOutage=await api.handle(adminRequest('page',memberToken),unavailableDb);
assert.equal(publicDuringOutage.status,200);
const publicOutageHtml=await publicDuringOutage.text();
assert.match(publicOutageHtml,/data-public-preview="true" data-admin="false"/);
assert.doesNotMatch(publicOutageHtml,/private-secret|owner@gmail\.com/);
const signedInWorkspace=await api.handle(adminRequest('page',memberToken),db);
assert.match(await signedInWorkspace.text(),/data-public-preview="false"/);
for(const [path,isAdmin] of [['admin?route=admin-page',true],['api/auth/start?route=start&destination=admin',true],['api/auth/callback?route=callback',false]]) {
 const req=new Request('https://relay.test/'+path+'&lang=en',{headers:{cookie:api.cookie(path.startsWith('api/auth/callback')?api.oauthCookie:api.sessionCookie,memberToken,600)}});
 const response=await api.handle(req,unavailableDb,config);
 assert.equal(response.status,503);assert.match(response.headers.get('content-type'),/text\/html/);
 const html=await response.text();assert.ok(html.includes('The sign-in service could not be reached'));
 assert.ok(!html.includes('private-secret')&&!html.includes('assets/app.js'));
 assert.ok(html.includes('/api/auth/start?lang=en'+(isAdmin?'&amp;destination=admin':'')));
 if(path.startsWith('api/auth/callback'))assert.match(response.headers.get('set-cookie'),/Max-Age=0/);
}
const priorFetch=globalThis.fetch;
try {
 globalThis.fetch=async()=>{throw new Error('private-provider-error');};
 const response=await api.handle(new Request('https://relay.test/api/auth/start?route=start&destination=admin&lang=ja'),db);
 assert.equal(response.status,503);assert.ok(!(await response.text()).includes('private-provider-error'));
} finally {globalThis.fetch=priorFetch;}
const canonical=await api.handle(new Request('https://old.test/admin?route=admin-page&lang=ar-EG&next=https://evil.test'),db);
assert.equal(canonical.headers.get('location'),'https://relay.test/admin?lang=ar-EG');
// A verified Google identity does not become an account denial when session storage fails.
const startBeforeFailure=await api.startLogin(db,config,'/admin');
const startUrl=new URL(startBeforeFailure.headers.get('location'));
const failedCookie=startBeforeFailure.headers.getSetCookie()[0].split(';')[0];
const [failedAttempt]=await db.query('SELECT verifier FROM relay_private.oauth_attempts WHERE token_hash=$1',[api.hash(failedCookie.split('=')[1])]);
expectedVerifier=failedAttempt.verifier;currentNonce=startUrl.searchParams.get('nonce');claimOverride={};tamper=false;
// Fail the actual INSERT inside SQL transactions as well as the old non-transactional path.
const oldSessionRequest=new Request('https://relay.test',{headers:{cookie:api.cookie(api.sessionCookie,memberToken,28800)}});
assert.deepEqual(await api.session(oldSessionRequest,db),second);
const sessionsBeforeFailure=await db.query('SELECT token_hash,subject,email,expires_at FROM relay_private.sessions ORDER BY token_hash');
let rejectedInserts=0;
const withFailedInsert=client=>({...client,query:(text,values)=>{
 if(text.startsWith('INSERT INTO relay_private.sessions')){rejectedInserts++;throw new Error('secret-db-error');}
 return client.query(text,values);
}});
const failWrites={...withFailedInsert(db),transaction:work=>db.transaction(tx=>work(withFailedInsert(tx)))};
const failedSession=await api.handle(new Request('https://relay.test/api/auth/callback?route=callback&code=synthetic&state='+startUrl.searchParams.get('state'),{headers:{cookie:failedCookie+'; '+api.sessionCookie+'='+memberToken}}),failWrites,config);
assert.equal(rejectedInserts,1,'The test must reach the failed session write');
assert.equal(failedSession.headers.get('location'),'/admin?auth=unavailable');
assert.equal(failedSession.headers.getSetCookie().some(value=>value.startsWith(api.sessionCookie+'=')),false);
assert.deepEqual(await api.session(oldSessionRequest,db),second,'Failed reauthentication preserves the previous session');
assert.deepEqual(await db.query('SELECT token_hash,subject,email,expires_at FROM relay_private.sessions ORDER BY token_hash'),sessionsBeforeFailure,'Partial session changes must roll back');
assert.equal((await db.query('SELECT token_hash FROM relay_private.oauth_attempts WHERE token_hash=$1',[api.hash(failedCookie.split('=')[1])])).length,0,'Failed persistence must not make the consumed Google callback reusable');
const retryPage=await api.handle(new Request('https://relay.test/admin?route=admin-page&auth=unavailable&lang=en',{headers:oldSessionRequest.headers}),db);
assert.equal(retryPage.status,503);
assert.ok((await retryPage.text()).includes('The sign-in service could not be reached'),'Previous member session must not hide an operational error behind permission denial');
const replacement=await callback({},false,false,'/admin',()=>{},memberToken);
assert.equal(replacement.result.headers.get('location'),'/admin');
assert.equal(await api.session(oldSessionRequest,db),null,'Successful reauthentication revokes the previous session');
const replacementCookie=replacement.result.headers.getSetCookie().find(value=>value.startsWith(api.sessionCookie+'='));
assert.ok(replacementCookie);
assert.deepEqual(await api.session(new Request('https://relay.test',{headers:{cookie:replacementCookie}}),db),owner);
for(const [outcome,status] of [['denied',403],['unavailable',503]]) {
 const feedback=await api.handle(new Request('https://relay.test/admin?route=admin-page&auth='+outcome,{headers:{cookie:replacementCookie}}),db);
 assert.equal(feedback.status,status);
 assert.ok(!(await feedback.text()).includes('assets/app.js'),'An existing admin session must not conceal a failed new sign-in');
}
const beforePreflight=await db.query('SELECT count(*)::int AS count FROM relay_private.sessions');
assert.equal(await api.loginDatabaseReady(db),true);
assert.deepEqual(await db.query('SELECT count(*)::int AS count FROM relay_private.sessions'),beforePreflight);
assert.equal(await api.loginDatabaseReady({query:async text=>text.includes('AS ready')?[{ready:false}]:[]}),false);
await assert.rejects(api.loginDatabaseReady(unavailableDb));
delete process.env.ADMIN_GOOGLE_EMAILS;
console.log('Admin: signed Google return path, anonymous/member denial, forged-role denial, dedicated allowlist, expiry/revocation, configuration redaction and page/API routing: OK.');
// No external network is used to prove fail-closed hosting.
delete process.env.GOOGLE_CLIENT_ID;delete process.env.GOOGLE_CLIENT_SECRET;delete process.env.DATABASE_URL;
for(const route of ['admin-overview','session','destinations','start','callback','calendar-status','calendar-callback','mcp-tokens']){
 const response=await api.endpoint.fetch(new Request('https://relay.test/api/relay?route='+route));assert.equal(response.status,503);assert.equal(response.headers.get('cache-control'),'private, no-store');
}
for(const route of ['notify','destination','logout','code','webhook','calendar-connect','calendar-disconnect','schedule-propose','schedule-book','mcp','mcp-token','mcp-revoke']){
 const response=await api.endpoint.fetch(new Request('https://relay.test/api/relay?route='+route,{method:'POST'}));assert.equal(response.status,503);
}
process.env.GOOGLE_CLIENT_ID='synthetic-client';process.env.GOOGLE_CLIENT_SECRET='synthetic-secret';process.env.DATABASE_URL='postgres://unused:unused@localhost/unused';
for(const route of ['admin-overview','session','destinations','calendar-status','calendar-callback','mcp-tokens'])assert.equal((await api.endpoint.fetch(new Request('https://relay.test/api/relay?route='+route))).status,401);
for(const route of ['logout','code','destination','notify','calendar-connect','calendar-disconnect','schedule-propose','schedule-book','mcp','mcp-token','mcp-revoke'])assert.equal((await api.endpoint.fetch(new Request('https://relay.test/api/relay?route='+route,{method:'POST'}))).status,401);
assert.equal((await api.endpoint.fetch(new Request('https://old-deployment.test/api/relay?route=session'))).status,403);
assert.equal((await api.endpoint.fetch(new Request('https://old-deployment.test/api/relay?route=page'))).headers.get('location'),'https://relay.test/');
delete process.env.GOOGLE_CLIENT_ID;
const publicEntry=await api.endpoint.fetch(new Request('https://relay.test/api/relay?route=page'));
assert.equal(publicEntry.status,200);assert.match(await publicEntry.text(),/data-public-preview="true" data-admin="false"/);
assert.equal(publicEntry.headers.get('Cache-Control'),'private, no-store');
const publicBundle=await api.endpoint.fetch(new Request('https://relay.test/api/relay?route=app'));
assert.equal(publicBundle.status,200);assert.match(publicBundle.headers.get('Content-Type'),/javascript/);
assert.doesNotMatch(await publicBundle.text(),/synthetic-secret|synthetic-line-token|owner@gmail\.com/);
for(const route of ['page','app']) assert.equal((await api.handle(new Request('https://relay.test/api/relay?route='+route,{method:'POST'}),db)).status,405);
for(const route of ['admin-overview','session','destinations','calendar-status','mcp-tokens']) assert.equal((await api.endpoint.fetch(new Request('https://relay.test/api/relay?route='+route+'&publicPreview=true'))).status,503);
const login=await api.endpoint.fetch(new Request('https://relay.test/api/relay?route=login-page'));const html=await login.text();assert.equal(login.status,503);assert.ok(!html.includes('assets/app.js'));assert.ok(!html.includes(owner.email));assert.ok(!html.includes('href="/api/auth/start"'));assert.match(html,/action="\/login"/);
await assert.rejects(api.limitedBody(new Request('https://relay.test',{method:'POST',body:'x'.repeat(65537)})),e=>e.status===413);
await pg.close();
console.log('Auth & LINE: real SQL migration, allowlist, verified claims, expiry/revocation, origin, signatures, pairing ownership/replay/expiry, group identity, notification idempotency/retry/quota and fail-closed routes: OK. No real messages sent.');

const validSettings={APP_ORIGIN:'https://relay.test',GOOGLE_CLIENT_ID:'synthetic-client',GOOGLE_CLIENT_SECRET:'synthetic-secret',DATABASE_URL:'postgres://fixture:secret@db.test/relay',ALLOWED_GOOGLE_EMAILS:'owner@gmail.com,second@gmail.com',ADMIN_GOOGLE_EMAILS:' OWNER@gmail.com '};
assert.deepEqual(api.authConfigurationIssues(validSettings),[]);
for (const field of Object.keys(validSettings)) assert.ok(api.authConfigurationIssues({...validSettings,[field]:' '}).some(issue=>issue.field===field&&issue.code==='missing'));
for(const value of ['*', 'owner@gmail.com,', 'owner@gmail.com\nsecond@gmail.com', 'not-an-email']) assert.ok(api.authConfigurationIssues({...validSettings,ADMIN_GOOGLE_EMAILS:value}).some(issue=>issue.code==='invalid'));
assert.deepEqual(api.authConfigurationIssues({...validSettings,ADMIN_GOOGLE_EMAILS:'other@gmail.com'}),[{field:'ADMIN_GOOGLE_EMAILS',code:'adminNotAllowed'}]);
for(const value of ['http://relay.test','https://user:password@relay.test','https://relay.test/admin','https://relay.test/?secret=x']) assert.ok(api.authConfigurationIssues({...validSettings,APP_ORIGIN:value}).some(issue=>issue.field==='APP_ORIGIN'&&issue.code==='invalid'));
assert.ok(api.authConfigurationIssues({...validSettings,DATABASE_URL:'https://db.test'}).some(issue=>issue.field==='DATABASE_URL'&&issue.code==='invalid'));
const diagnostics=JSON.stringify(api.authConfigurationIssues({...validSettings,ADMIN_GOOGLE_EMAILS:'private@gmail.com',DATABASE_URL:'private-secret'}));
assert.ok(!diagnostics.includes('private@gmail.com')&&!diagnostics.includes('private-secret'));
console.log('Admin configuration: exact addresses, malformed lists, subset validation, unset permissions, Google callback rejection and redacted diagnostics: OK.');
for (const [settings,expected] of [[validSettings,0],[{...validSettings,ADMIN_GOOGLE_EMAILS:'private@gmail.com'},1]]) {
 const check=spawnSync(process.execPath,['scripts/check-auth-config.mjs'],{env:{...process.env,...settings},encoding:'utf8'});
 assert.equal(check.status,expected);
 assert.ok(!(check.stdout+check.stderr).includes('private@gmail.com'));
 assert.ok(!(check.stdout+check.stderr).includes('synthetic-secret'));
 if(expected===1) assert.match(check.stderr,/ADMIN_GOOGLE_EMAILS: adminNotAllowed/);
}

const mismatch=spawnSync(process.execPath,['scripts/check-auth-config.mjs','--deployment'],{env:{...process.env,...validSettings,DATABASE_URL:'invalid-fixture-url'},encoding:'utf8'});
assert.equal(mismatch.status,1);assert.match(mismatch.stderr,/APP_ORIGIN: publicOriginMismatch/);
assert.ok(!mismatch.stderr.includes(validSettings.APP_ORIGIN));
assert.match(mismatch.stderr,/DATABASE_URL: invalid/);
assert.doesNotMatch(mismatch.stderr,/connectionSchemaOrPermissions/);
// A separate OAuth configuration error must not hide a database connection failure.
const independent=spawnSync(process.execPath,['scripts/check-auth-config.mjs','--deployment'],{env:{...process.env,...validSettings,GOOGLE_CLIENT_SECRET:'',DATABASE_URL:'postgres://fixture:private-fixture-password@127.0.0.1:1/relay'},encoding:'utf8',timeout:15000});
assert.equal(independent.status,1);
assert.match(independent.stderr,/GOOGLE_CLIENT_SECRET: missing/);
assert.match(independent.stderr,/DATABASE_URL: connectionSchemaOrPermissions/);
assert.doesNotMatch(independent.stdout+independent.stderr,/private-fixture-password|127\.0\.0\.1|synthetic-client|owner@gmail\.com/);
