import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {createHmac,randomUUID,generateKeyPairSync,sign} from 'node:crypto';
import * as oidc from 'openid-client';
import {PGlite} from '@electric-sql/pglite';
await mkdir('.vercel/check-auth',{recursive:true});
await build({stdin:{contents:`export * from './src/server/config'; export * from './src/server/auth'; export * from './src/server/line'; export {default as endpoint,limitedBody} from './src/server/handler';`,resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',packages:'external',outfile:'.vercel/check-auth/server.mjs'});
const api=await import(pathToFileURL(process.cwd()+'/.vercel/check-auth/server.mjs'));
const pg=new PGlite();
const wrap=client=>({query:async(text,values)=>(await client.query(text,values)).rows,transaction:work=>client.transaction(tx=>work(wrap(tx)))});
const db=wrap(pg);
await pg.exec(await readFile('migrations/001_identity_line.sql','utf8'));
// Synthetic identities only; the production allowlist is never loaded here.
process.env.ALLOWED_GOOGLE_EMAILS='owner@gmail.com, second@gmail.com';
process.env.APP_ORIGIN='https://relay.test';
process.env.LINE_CHANNEL_SECRET='synthetic-line-secret';
process.env.LINE_CHANNEL_ACCESS_TOKEN='synthetic-line-token';
const owner={email:'owner@gmail.com',subject:'subject-one'},second={email:'second@gmail.com',subject:'subject-two'};
assert.equal(api.allowed('Owner@gmail.com'),true);
for(const email of ['owner@gmail.com.evil','other@gmail.com','',null,{},['owner@gmail.com']])assert.equal(api.allowed(email),false);
assert.equal(api.allowed('owner@gmail.com',''),false);
assert.equal(api.sameOrigin(new Request('https://relay.test/api',{headers:{origin:'https://evil.test'}})),false);
assert.equal(api.sameOrigin(new Request('https://relay.test/api',{headers:{origin:'https://relay.test'}})),true);
for(const profile of [{email:owner.email,email_verified:false,sub:'1'},{email:'other@gmail.com',email_verified:true,sub:'1'},{email:owner.email,email_verified:'true',sub:'1'},{email:owner.email,email_verified:true}])assert.equal(api.verifiedIdentity(profile),null);
assert.deepEqual(api.verifiedIdentity({email:owner.email,email_verified:true,sub:owner.subject}),owner);
const token=api.randomToken();
const request=new Request('https://relay.test/api/session',{headers:{cookie:api.cookie(api.sessionCookie,token,28800)}});
await db.query("INSERT INTO relay_private.sessions VALUES($1,$2,$3,now()+interval '1 hour')",[api.hash(token),owner.subject,owner.email]);
assert.deepEqual(await api.session(request,db),owner);
assert.equal(await api.session(new Request('https://relay.test'),db),null);
assert.equal(await api.session(new Request('https://relay.test',{headers:{cookie:api.cookie(api.sessionCookie,api.randomToken(),28800)}}),db),null);
process.env.ALLOWED_GOOGLE_EMAILS=second.email;assert.equal(await api.session(request,db),null);process.env.ALLOWED_GOOGLE_EMAILS=owner.email+','+second.email;
await db.query("UPDATE relay_private.sessions SET expires_at=now()-interval '1 second'");assert.equal(await api.session(request,db),null);
await db.query("UPDATE relay_private.sessions SET expires_at=now()+interval '1 hour'");await api.logout(request,db);assert.equal(await api.session(request,db),null);
// Drive the actual OIDC library with a signed synthetic provider, with no network.
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});
const config=new oidc.Configuration({issuer:'https://accounts.google.com',authorization_endpoint:'https://accounts.google.com/o/oauth2/v2/auth',token_endpoint:'https://oauth.test/token',jwks_uri:'https://oauth.test/keys',id_token_signing_alg_values_supported:['RS256']},'test-client','test-secret');
oidc.enableNonRepudiationChecks(config);
let currentNonce='',claimOverride={},tamper=false,expectedVerifier='';
const base64=value=>Buffer.from(JSON.stringify(value)).toString('base64url');
config[oidc.customFetch]=async(url,options)=>{
 if(String(url)==='https://oauth.test/keys')return Response.json({keys:[{...publicKey.export({format:'jwk'}),kid:'test-key',use:'sig',alg:'RS256'}]});
 assert.equal(String(url),'https://oauth.test/token');
 assert.equal(new URLSearchParams(options.body).get('code_verifier'),expectedVerifier);
 const now=Math.floor(Date.now()/1000);
 const payload=base64({alg:'RS256',kid:'test-key'})+'.'+base64({iss:'https://accounts.google.com',aud:'test-client',sub:owner.subject,email:owner.email,email_verified:true,nonce:currentNonce,iat:now,exp:now+300,...claimOverride});
 const signature=sign('RSA-SHA256',Buffer.from(payload),privateKey).toString('base64url');
 return Response.json({access_token:'synthetic-access',token_type:'Bearer',id_token:payload+'.'+(tamper?'AAAA'+signature.slice(4):signature)});
};
async function callback(overrides={},badState=false,badSignature=false){
 claimOverride=overrides;tamper=badSignature;
 const start=await api.startLogin(db,config);
 const authorization=new URL(start.headers.get('location'));
 assert.equal(authorization.searchParams.get('code_challenge_method'),'S256');
 assert.equal(authorization.searchParams.get('scope'),'openid email');
 const browserCookie=start.headers.get('set-cookie').split(';')[0];
 const attempt=(await db.query('SELECT verifier FROM relay_private.oauth_attempts WHERE token_hash=$1',[api.hash(browserCookie.split('=')[1])]))[0];expectedVerifier=attempt.verifier;
 currentNonce=authorization.searchParams.get('nonce');
 const req=new Request('https://relay.test/api/auth/callback?code=synthetic&state='+(badState?'wrong-state':authorization.searchParams.get('state')),{headers:{cookie:browserCookie}});
 return {result:await api.finishLogin(req,db,config),req};
}
const success=await callback();assert.equal(success.result.headers.get('location'),'/');
const sessionHeader=success.result.headers.getSetCookie().find(value=>value.startsWith(api.sessionCookie+'='));
assert.ok(sessionHeader);assert.deepEqual(await api.session(new Request('https://relay.test',{headers:{cookie:sessionHeader}}),db),owner);
assert.equal((await api.finishLogin(success.req,db,config)).headers.get('location'),'/?auth=denied');
for(const overrides of [{email:'intruder@gmail.com'},{email_verified:false},{nonce:'wrong-nonce'},{aud:'different-client'},{iss:'https://evil.test'},{exp:1}])assert.equal((await callback(overrides)).result.headers.get('location'),'/?auth=denied');
assert.equal((await callback({},true)).result.headers.get('location'),'/?auth=denied');
assert.equal((await callback({},false,true)).result.headers.get('location'),'/?auth=denied');
const noCallback=await api.finishLogin(new Request('https://relay.test/api/auth/callback?code=forged&state=forged'),db);assert.equal(noCallback.headers.get('location'),'/?auth=denied');
assert.match(noCallback.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);
assert.equal(api.validSignature('{}',null,process.env.LINE_CHANNEL_SECRET),false);
const signature=raw=>createHmac('sha256',process.env.LINE_CHANNEL_SECRET).update(raw).digest('base64');
assert.equal(api.validSignature('{}',signature('{}'),process.env.LINE_CHANNEL_SECRET),true);
assert.equal(api.validSignature('{ }',signature('{}'),process.env.LINE_CHANNEL_SECRET),false);
await assert.rejects(api.webhook('{"events":[]}',signature('{}'),db),e=>e.status===401);
await api.webhook('{"events":[]}',signature('{"events":[]}'),db);
await assert.rejects(api.issueCode(owner,'group',db),e=>e.code==='personalFirst');
const event=(code,kind='user',actor='U-personal',id=randomUUID())=>({webhookEventId:id,type:'message',source:{type:kind,userId:actor,...(kind==='group'?{groupId:'C-group'}:{})},message:{type:'text',text:code}});
const deliver=async(...events)=>{const raw=JSON.stringify({events});await api.webhook(raw,signature(raw),db)};
const code=await api.issueCode(owner,'user',db);
const link=event(code.code);
await deliver(link);let rows=await api.destinations(owner,db);assert.equal(rows.length,1);assert.equal(rows[0].enabled,false);
await deliver(link);assert.equal((await api.destinations(owner,db))[0].id,rows[0].id);
await deliver(event(code.code));assert.equal((await api.destinations(owner,db))[0].id,rows[0].id,'Consumed code must not create a new link');
await assert.rejects(api.changeDestination(second,rows[0].id,'confirm',db),e=>e.status===404);
await api.changeDestination(owner,rows[0].id,'confirm',db);
const groupCode=await api.issueCode(owner,'group',db);
await deliver(event(groupCode.code,'group','U-attacker'));assert.equal((await api.destinations(owner,db)).length,1);
await deliver(event(groupCode.code,'group'));rows=await api.destinations(owner,db);assert.equal(rows.length,2);
const group=rows.find(row=>row.kind==='group');
await api.changeDestination(owner,group.id,'confirm',db);
const personal=rows.find(row=>row.kind==='user');
let sends=0;
const sentRequests=[];
const sender=async(url,options)=>{sends++;sentRequests.push({url,options});return new Response('{}',{status:200})};
const notification={id:randomUUID(),destinationId:group.id,locale:'ja'};
await assert.rejects(api.notify(second,notification,db,sender),e=>e.status===404);assert.equal(sends,0);
await api.notify(owner,notification,db,sender);await api.notify(owner,notification,db,sender);assert.equal(sends,1);
assert.equal(sentRequests[0].url,'https://api.line.me/v2/bot/message/push');assert.equal(sentRequests[0].options.headers['X-Line-Retry-Key'],notification.id);
assert.equal(JSON.parse(sentRequests[0].options.body).to,'C-group');
await assert.rejects(api.notify(owner,{...notification,destinationId:personal.id},db,sender),e=>e.code==='conflict');
const retry={...notification,id:randomUUID()};
await assert.rejects(api.notify(owner,retry,db,async()=>{throw new Error('timeout')}),e=>e.code==='delivery');
const accepted=async(_url,options)=>{assert.equal(options.headers['X-Line-Retry-Key'],retry.id);return new Response('{}',{status:409,headers:{'x-line-accepted-request-id':'accepted'}})};
await api.notify(owner,retry,db,accepted);assert.equal((await db.query('SELECT state FROM relay_private.notifications WHERE id=$1',[retry.id]))[0].state,'sent');
const bad={...notification,id:randomUUID()};await assert.rejects(api.notify(owner,bad,db,async()=>new Response('{}',{status:400})),e=>e.code==='delivery');
await assert.rejects(api.notify(owner,bad,db,sender),e=>e.code==='pending');
for(let i=0;i<7;i++)await api.notify(owner,{...notification,id:randomUUID()},db,sender);
await assert.rejects(api.notify(owner,{...notification,id:randomUUID()},db,sender),e=>e.code==='rateLimit');
await deliver({webhookEventId:randomUUID(),type:'leave',source:{type:'group',groupId:'C-group'}});
await assert.rejects(api.changeDestination(owner,group.id,'confirm',db),e=>e.status===404);
await api.changeDestination(owner,personal.id,'remove',db);assert.equal((await api.destinations(owner,db)).length,0);
const expiring=await api.issueCode(owner,'user',db);await db.query("UPDATE relay_private.line_codes SET expires_at=now()-interval '1 minute'");await deliver(event(expiring.code));assert.equal((await api.destinations(owner,db)).length,0);
const revoked=await api.issueCode(owner,'user',db);process.env.ALLOWED_GOOGLE_EMAILS=second.email;await deliver(event(revoked.code));assert.equal((await api.destinations(owner,db)).length,0);
// No external network is used to prove fail-closed hosting.
delete process.env.GOOGLE_CLIENT_ID;delete process.env.GOOGLE_CLIENT_SECRET;delete process.env.DATABASE_URL;
for(const route of ['app','session','destinations','start','callback','calendar-status','calendar-callback','mcp-tokens']){
 const response=await api.endpoint.fetch(new Request('https://relay.test/api/relay?route='+route));assert.equal(response.status,503);assert.equal(response.headers.get('cache-control'),'private, no-store');
}
for(const route of ['notify','destination','logout','code','webhook','calendar-connect','calendar-disconnect','schedule-propose','schedule-book','mcp','mcp-token','mcp-revoke']){
 const response=await api.endpoint.fetch(new Request('https://relay.test/api/relay?route='+route,{method:'POST'}));assert.equal(response.status,503);
}
process.env.GOOGLE_CLIENT_ID='synthetic-client';process.env.GOOGLE_CLIENT_SECRET='synthetic-secret';process.env.DATABASE_URL='postgres://unused:unused@localhost/unused';
for(const route of ['app','session','destinations','calendar-status','calendar-callback','mcp-tokens'])assert.equal((await api.endpoint.fetch(new Request('https://relay.test/api/relay?route='+route))).status,401);
for(const route of ['logout','code','destination','notify','calendar-connect','calendar-disconnect','schedule-propose','schedule-book','mcp','mcp-token','mcp-revoke'])assert.equal((await api.endpoint.fetch(new Request('https://relay.test/api/relay?route='+route,{method:'POST'}))).status,401);
assert.equal((await api.endpoint.fetch(new Request('https://old-deployment.test/api/relay?route=session'))).status,403);
assert.equal((await api.endpoint.fetch(new Request('https://old-deployment.test/api/relay?route=page'))).headers.get('location'),'https://relay.test/');
delete process.env.GOOGLE_CLIENT_ID;
const login=await api.endpoint.fetch(new Request('https://relay.test/api/relay?route=page'));const html=await login.text();assert.equal(login.status,200);assert.ok(!html.includes('assets/app.js'));assert.ok(!html.includes(owner.email));assert.ok(!html.includes('href="/api/auth/start"'));
await assert.rejects(api.limitedBody(new Request('https://relay.test',{method:'POST',body:'x'.repeat(65537)})),e=>e.status===413);
await pg.close();
console.log('Auth & LINE: real SQL migration, allowlist, verified claims, expiry/revocation, origin, signatures, pairing ownership/replay/expiry, group identity, notification idempotency/retry/quota and fail-closed routes: OK. No real messages sent.');
