import {translate,brand,localeNames,type Locale,type MessageKey} from '../i18n/messages';
import {initialCases,sourceMessage,demoMembers,demoMeta,type CaseRecord} from './data';
type Page='today'|'cases'|'reviews'|'imports'|'system'|'detail';
const state={locale:'ja' as Locale,page:'today' as Page,caseId:1,cases:structuredClone(initialCases),review:'pending',reviewOwner:demoMembers[0],reviewDue:'dueNow' as 'dueNow'|'futureDate'|'dueUnknown',imported:false,search:'',owner:'',filter:'all',drafts:{} as Record<number,string>,error:'',notice:'',mobileOpen:false};
const root=document.getElementById('app');if(!root)throw new Error('Missing app root');
const app:HTMLElement=root;
const t=(k:MessageKey,p:Record<string,string|number>={})=>translate(state.locale,k,p);
const esc=(s:string|number)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const paths:Record<string,string>={home:'M3 10 12 3l9 7v10H3Z M9 20v-7h6v7',cases:'M3 5h7l2 3h9v12H3Z',reviews:'m5 12 4 4L19 6 M3 3h18v18H3Z',imports:'M12 16V3 m-5 5 5-5 5 5 M3 15v6h18v-6',system:'M4 5h16 M4 12h16 M4 19h16 M8 3v4 M16 10v4 M9 17v4',arrow:'M4 12h16 m-6-6 6 6-6 6',back:'M20 12H4 m6-6-6 6 6 6',close:'m6 6 12 12 M6 18 18 6',menu:'M4 6h16 M4 12h16 M4 18h16',spark:'m12 3 3 6 6 3-6 3-3 6-3-6-6-3 6-3Z'};
const icon=(name:string)=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]??paths.arrow}"></path></svg>`;
const link=(text:MessageKey,href:string,primary=false)=>`<a class="button ${primary?'primary':''}" href="${href}">${t(text)}${icon('arrow')}</a>`;
const button=(text:MessageKey,action:string,variant='')=>`<button class="button ${variant}" data-action="${action}">${t(text)}</button>`;
const pill=(text:string,variant='')=>`<span class="pill ${variant}">${esc(text)}</span>`;
const duePill=(c:CaseRecord)=>pill(t(c.due),c.level==='overdue'?'error':c.level==='today'?'warning':'');
const ownerName=(c:CaseRecord)=>c.owner||t('unknown');
const header=(title:MessageKey,sub:MessageKey,action='')=>`<header class="page-head"><div><h1 id="page-title" tabindex="-1">${t(title)}</h1><p>${t(sub)}</p></div>${action}</header>`;
const current=()=>state.cases.find(c=>c.id===state.caseId)??state.cases[0];
function renderShell(){
 document.documentElement.lang=state.locale;document.title=t('app');
 const navs:readonly [Page,MessageKey,string][]=[['today','today','home'],['cases','cases','cases'],['reviews','reviews','reviews'],['imports','imports','imports'],['system','system','system']];
 app.innerHTML=`<a class="button skip" href="#main">${t('skip')}</a><div class="app"><aside class="sidebar ${state.mobileOpen?'open':''}"><div class="sidebar-top"><a class="brand" href="#today" aria-label="${brand}"><svg class="brand-mark" viewBox="0 0 32 32" aria-hidden="true"><path d="M4 23V9h9a6 6 0 0 1 0 12H9 M15 21l7 7 M20 4h8v15"></path></svg>${brand}</a><button class="icon-button mobile-toggle" data-action="menu" aria-label="${t('menu')}" aria-controls="main-nav" aria-expanded="${state.mobileOpen}">${icon('menu')}</button></div><p class="workspace">${t('workspace')}</p><nav id="main-nav" aria-label="${t('menu')}">${navs.map(([p,k,i])=>`<a class="nav-link" href="#${p}" ${state.page===p?'aria-current="page"':''}>${icon(i)}${t(k)}${p==='reviews'?`<span class="count">${state.review==='pending'?'01':'00'}</span>`:''}</a>`).join('')}</nav><div class="sidebar-bottom"><p>${t('tagline')}</p><div class="member"><span class="avatar">R</span><div>${t('member')}<br><span class="small">${t('memberRole')}</span></div></div></div></aside><main id="main" tabindex="-1"><div class="topbar"><p class="meta">${t('tagline')}</p><div class="top-actions"><span class="pill">${t('demo')}</span><label class="sr-only" for="locale">${t('language')}</label><select id="locale" class="locale-select"><option value="ja" ${state.locale==='ja'?'selected':''}>${localeNames.ja}</option><option value="en" ${state.locale==='en'?'selected':''}>${localeNames.en}</option></select></div></div><div id="page">${renderPage()}</div><p class="footer-note">${t('demoNote')} · ${t('previewFooter')}</p></main></div><dialog id="modal" aria-labelledby="modal-title"><div class="dialog-head"><h2 id="modal-title"></h2><button class="icon-button" data-action="close" aria-label="${t('close')}">${icon('close')}</button></div><div id="modal-body" class="dialog-body"></div></dialog><div id="toast" class="toast" role="status" aria-live="polite" hidden></div>`;
}
function task(c:CaseRecord,index:number){return `<article class="task"><span class="task-number">${String(index+1).padStart(2,'0')}</span><div><div class="row space-between"><p class="meta">${esc(c.name)} · ${esc(c.area)}</p>${duePill(c)}</div><h3 class="task-title">${esc(c.title)}</h3><p class="meta">${esc(c.reason)}</p><div class="task-foot"><div class="row"><span class="meta">${esc(ownerName(c))}</span>${pill(t(c.status))}</div><a class="button quiet" href="#case/${c.id}">${t('open')}${icon('arrow')}</a></div></div></article>`}
function today(){const active=state.cases.filter(c=>c.status!=='done');const due=active.filter(c=>['today','overdue'].includes(c.level)).sort((a,b)=>Number(b.level==='overdue')-Number(a.level==='overdue'));return header('todayTitle','todaySub',link('add','#imports',true))+`<section class="metrics" aria-label="${t('today')}">${([['dueToday',due.length,'todayHint'],['overdue',active.filter(c=>c.level==='overdue').length,'overdueHint'],['unassigned',active.filter(c=>c.level==='unknown').length,'unassignedHint']] as const).map(([k,v,h])=>`<div class="metric"><p class="metric-label">${t(k)}</p><p class="metric-value">${v}<small> ${t('unit')}</small></p><p class="meta small">${t(h)}</p></div>`).join('')}</section><div class="main-grid"><section class="column"><div class="section-head"><h2>${t('priority')}</h2><span class="meta small">${t('asOf')}</span></div>${due.length?due.map(task).join(''):`<div class="empty"><h2>${t('emptyToday')}</h2><p>${t('emptyTodaySub')}</p>${link('browse','#cases')}</div>`}<p class="footer-note">${t('sourceHint')}</p></section><aside class="aside"><section class="panel"><p class="eyeline">${icon('spark')}${t('assistant')}</p><h3>${t('assistantTitle')}</h3><p class="meta">${t('assistantBody')}</p>${link('reviewOpen','#reviews')}</section><section class="panel inverse block-gap"><h3>${t('handoffTitle')}</h3><p class="meta">${t('handoffBody')}</p>${link('browse','#cases')}</section></aside></div>`}
function filtered(){return state.cases.filter(c=>(!state.owner||c.owner===state.owner)&&`${c.name} ${c.area} ${c.title}`.toLocaleLowerCase().includes(state.search.toLocaleLowerCase())&&(state.filter==='all'||(state.filter==='unknown'?!c.owner:['today','overdue'].includes(c.level)&&c.status!=='done')))}
function rows(){const data=filtered();return data.length?data.map(c=>`<tr><td><a class="details-link" href="#case/${c.id}">${esc(c.name)}</a><p class="meta">${esc(c.area)}</p></td><td><span class="meta">${t(c.stage)}</span></td><td>${esc(c.title)}<p class="meta">${t(c.status)}</p></td><td>${esc(ownerName(c))}</td><td>${duePill(c)}</td></tr>`).join(''):`<tr><td colspan="5"><div class="empty"><h3>${t('noResults')}</h3><p>${t('noResultsSub')}</p>${button('resetFilters','reset')}</div></td></tr>`}
function cases(){return header('casesTitle','casesSub')+`<div class="toolbar"><label class="sr-only" for="search">${t('search')}</label><input class="search" id="search" type="search" value="${esc(state.search)}" placeholder="${t('search')}"><label class="sr-only" for="owner">${t('owner')}</label><select id="owner"><option value="">${t('allOwners')}</option>${[...new Set(state.cases.map(c=>c.owner).filter(Boolean))].map(o=>`<option ${state.owner===o?'selected':''}>${esc(o)}</option>`).join('')}</select></div><div class="row space-between"><div class="filters">${(['all','needsAttention','unknown'] as const).map(k=>`<button class="filter" data-filter="${k}" aria-pressed="${state.filter===k}">${t(k)}</button>`).join('')}</div><span class="meta" id="result-count" role="status">${t('count',{count:filtered().length})}</span></div><div class="table-region" tabindex="0" role="region" aria-label="${t('cases')}"><table><thead><tr>${(['name','stage','action','owner','due'] as const).map(k=>`<th scope="col">${t(k)}</th>`).join('')}</tr></thead><tbody id="case-rows">${rows()}</tbody></table></div>`}
const fact=(key:MessageKey,value:string)=>`<div class="fact"><dt>${t(key)}</dt><dd>${esc(value)}</dd></div>`;
function details(){const c=current();return `<div class="block-gap"><a class="button quiet" href="#cases">${icon('back')}${t('back')}</a></div><header class="page-head"><div><div class="row">${pill(t(c.stage))}${pill(t(c.status),c.status==='done'?'success':'')}</div><h1 id="page-title" tabindex="-1" class="block-gap">${esc(c.name)}</h1><p>${esc(c.area)} · ${t('detailSub')}</p></div>${button('handoff','handoff')}</header><div class="detail-grid"><section><p class="eyeline">${t('summary')}</p><h2>${esc(c.title)}</h2><p class="muted block-gap">${esc(c.reason)}</p><dl class="fact-grid">${fact('owner',ownerName(c))}${fact('due',t(c.due))}${fact('waiting',c.waiting)}${fact('next',c.next)}</dl><section class="layout-section"><div class="section-head"><h2>${t('timeline')}</h2></div><ol class="timeline">${c.history.map(([d,b])=>`<li><span class="meta">${esc(d)}</span><p>${esc(b)}</p></li>`).join('')}</ol></section><section class="layout-section"><div class="section-head"><h2>${t('evidence')}</h2></div><div class="evidence"><small class="meta">${t('evidenceOrigin')}</small><p>${esc(c.evidence)}</p></div></section>${c.notes.length?`<section class="layout-section"><h3>${t('reports')}</h3>${c.notes.map(n=>`<div class="evidence"><small>${t('reported')}</small><p>${esc(n)}</p></div>`).join('')}</section>`:''}</section><aside><div class="panel"><h3>${t('record')}</h3><p class="meta">${t('recordSub')}</p><div class="field block-gap"><label for="report">${t('recordLabel')}</label><textarea id="report" aria-describedby="report-error report-help" aria-invalid="${Boolean(state.error)}" placeholder="${t('recordPlaceholder')}">${esc(state.drafts[c.id]??'')}</textarea><p id="report-error" class="field-error" ${state.error?'':'hidden'}>${esc(state.error)}</p><p class="meta" id="report-help">${t('reportHint')}</p></div><div class="form-actions">${button('save','save','primary')}<button class="button" data-action="complete" ${c.status==='done'?'disabled':''}>${t(c.status==='done'?'completed':'complete')}</button></div>${state.notice?`<p class="notice success block-gap" role="status">${esc(state.notice)}</p>`:''}</div></aside></div>`}
function reviews(){if(state.review!=='pending')return header('reviewTitle','reviewSub')+`<div class="empty"><h2>${t(state.review==='approved'?'reviewComplete':'reviewRejected')}</h2><p>${t('reviewEmpty')}</p>${link('open','#case/1')}</div>`;return header('reviewTitle','reviewSub')+`<div class="reading"><div class="row space-between">${pill(t('proposal'),'info')}<span class="meta">${demoMeta.messageTime}</span></div><h2 class="block-gap">${t('proposalHeading')}</h2><div class="diff"><section class="diff-side"><span class="meta">${t('before')}</span><p>${t('beforeText')}</p><div class="block-gap">${pill(t('customerPending'))}</div></section><section class="diff-side after"><span class="meta">${t('after')}</span><p>${t('afterText')}</p><div class="block-gap">${pill(t('customerAgreed'),'info')}</div></section></div><h3>${t('evidence')}</h3><div class="evidence"><small class="meta">${t('evidenceOrigin')}</small><p>${esc(sourceMessage)}</p></div>${button('showEvidence','evidence','quiet')}<div class="split block-gap"><div class="field"><label for="review-owner">${t('owner')}</label><select id="review-owner">${demoMembers.map(n=>`<option ${state.reviewOwner===n?'selected':''}>${n}</option>`).join('')}</select></div><div class="field"><label for="review-due">${t('due')}</label><select id="review-due"><option value="dueNow" ${state.reviewDue==='dueNow'?'selected':''}>${t('dueNow')}</option><option value="futureDate" ${state.reviewDue==='futureDate'?'selected':''}>${t('futureDate')}</option><option value="dueUnknown" ${state.reviewDue==='dueUnknown'?'selected':''}>${t('dueUnknown')}</option></select></div></div><p class="meta block-gap">${t('reviewOwnerHint')}</p><p class="notice warning block-gap">${t('reviewCaution')}</p>${state.error?`<p class="notice error block-gap" role="alert">${esc(state.error)}</p>`:''}<div class="form-actions">${button('approve','approve','primary')}${button('reject','reject')}</div><p class="footer-note">${t('reviewNoSend')}</p></div>`}
function imports(){return header('importTitle','importSub')+`<div class="reading"><p class="eyeline">${icon('imports')}${t('history')}</p><div class="dropzone">${icon('imports')}<h2>${t('dropTitle')}</h2><p>${t('dropSub')}</p>${button(state.imported?'sampleShown':'sample','sample','primary')}</div><div class="flow-steps">${(['step1','step2','step3','step4'] as const).map((k,i)=>`<div class="step"><span class="step-number">0${i+1}</span><p>${t(k)}</p></div>`).join('')}</div>${state.imported?`<section class="section-gap"><h2>${t('imported')}</h2><dl class="fact-grid">${fact('file',demoMeta.fileName)}${fact('period',demoMeta.referenceDate)}${fact('duplicates',t('two'))}${fact('newMessages',t('one'))}</dl><p class="notice">${t('importNote')}</p><div class="block-gap">${link('reviewOpen','#reviews')}</div></section>`:''}<p class="footer-note">${t('historyNote')}</p></div>`}
function system(){return header('systemTitle','systemSub')+`<div class="split">${([['palette','paletteBody'],['platform','platformBody'],['sequencing','sequencingBody'],['reusable','reusableBody']] as const).map(([h,b],i)=>`<section class="panel ${i===2?'inverse':''}"><p class="meta">0${i+1}</p><h2 class="block-gap">${t(h)}</h2><p class="block-gap">${t(b)}</p></section>`).join('')}</div><div class="row section-gap"><a class="button" href="../docs/DESIGN_GUIDELINES.md">${t('guide')}${icon('arrow')}</a><a class="button" href="../docs/STACK_DECISION.md">${t('architecture')}${icon('arrow')}</a></div>`}
function renderPage(){return ({today,cases,reviews,imports,system,detail:details}[state.page])()}
function rerenderPage(){const target=document.getElementById('page');if(target)target.innerHTML=renderPage()}
function refreshRows(){const target=document.getElementById('case-rows');if(target)target.innerHTML=rows();const count=document.getElementById('result-count');if(count)count.textContent=t('count',{count:filtered().length})}
let toastTimer:number|undefined;
function toast(message:string){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.hidden=false;window.clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>{el.hidden=true},4000)}
let modalReturn:HTMLElement|null=null;
function modal(title:MessageKey,body:string){modalReturn=document.activeElement instanceof HTMLElement?document.activeElement:null;const el=document.getElementById('modal') as HTMLDialogElement;document.getElementById('modal-title')!.textContent=t(title);document.getElementById('modal-body')!.innerHTML=body;el.showModal();el.addEventListener('close',()=>modalReturn?.focus(),{once:true})}
function handoffText(){const c=current();return `${c.name}\n${t('stage')}: ${t(c.stage)}\n${t('action')}: ${c.title}\n${t('status')}: ${t(c.status)}\n${t('owner')}: ${ownerName(c)}\n${t('waiting')}: ${c.waiting}\n${t('due')}: ${t(c.due)}\n${t('next')}: ${c.next}\n${t('evidence')}: ${c.evidence}\n${t('reports')}: ${c.notes.at(-1)??t('noReport')}\n\n${t('handoffCaution')}`}
function route(){const hash=location.hash.slice(1);if(hash==='main')return;if(hash.startsWith('case/')){state.page='detail';state.caseId=state.cases.find(c=>c.id===Number(hash.split('/')[1]))?.id??1}else state.page=(['today','cases','reviews','imports','system'].includes(hash)?hash:'today') as Page;state.error='';state.notice='';state.mobileOpen=false;renderShell();document.getElementById('page-title')?.focus({preventScroll:true});window.scrollTo(0,0)}
document.addEventListener('input',e=>{const el=e.target;if(el instanceof HTMLInputElement&&el.id==='search'){state.search=el.value;refreshRows()}if(el instanceof HTMLTextAreaElement&&el.id==='report')state.drafts[state.caseId]=el.value});
document.addEventListener('change',e=>{const el=e.target;if(!(el instanceof HTMLSelectElement))return;if(el.id==='locale'){state.locale=el.value==='en'?'en':'ja';state.error='';state.notice='';renderShell();document.getElementById('locale')?.focus()}if(el.id==='review-owner')state.reviewOwner=el.value;if(el.id==='review-due'&&['dueNow','futureDate','dueUnknown'].includes(el.value))state.reviewDue=el.value as typeof state.reviewDue;if(el.id==='owner'){state.owner=el.value;refreshRows()}});
document.addEventListener('click',async e=>{const target=e.target instanceof Element?e.target.closest('button'):null;if(!target)return;
 if(target.dataset.filter){state.filter=target.dataset.filter;rerenderPage();document.querySelector<HTMLElement>(`[data-filter="${state.filter}"]`)?.focus();return}
 switch(target.dataset.action){
 case'menu':state.mobileOpen=!state.mobileOpen;document.querySelector('.sidebar')?.classList.toggle('open',state.mobileOpen);target.setAttribute('aria-expanded',String(state.mobileOpen));break;
 case'reset':state.search='';state.owner='';state.filter='all';rerenderPage();document.getElementById('search')?.focus();break;
 case'sample':state.imported=true;rerenderPage();document.querySelector<HTMLElement>('[data-action="sample"]')?.focus();break;
 case'close':(document.getElementById('modal') as HTMLDialogElement).close();break;
 case'evidence':modal('evidence',`<p class="meta">${t('evidenceOrigin')}</p><div class="evidence"><p>${esc(sourceMessage)}</p></div><p class="notice">${t('reviewCaution')}</p>`);break;
 case'handoff':modal('handoffHeading',`<p class="pre" id="handoff-text">${esc(handoffText())}</p><div class="block-gap">${button('copy','copy','primary')}</div>`);break;
 case'copy':try{await navigator.clipboard.writeText(handoffText());toast(t('copied'))}catch{toast(t('copyError'))}break;
 case'reject':state.review='rejected';renderShell();document.getElementById('page-title')?.focus();break;
 case'approve':{const c=state.cases[0];if(c.version!==1){state.error=t('reviewConflict');rerenderPage();break}const owner=(document.getElementById('review-owner') as HTMLSelectElement).value;const due=(document.getElementById('review-due') as HTMLSelectElement).value as MessageKey;c.owner=owner;c.due=due;c.level=due==='dueNow'?'today':due==='dueUnknown'?'unknown':'upcoming';c.status='todo';c.title=translate('ja','afterText');c.reason=translate('ja','reviewCaution');c.waiting='—';c.evidence=sourceMessage;c.version++;c.history=[...c.history,[demoMeta.messageTime,sourceMessage]];state.review='approved';renderShell();document.getElementById('page-title')?.focus();break}
 case'save':case'complete':{const c=current();const value=(state.drafts[c.id]??'').trim();if(value.length<5){state.error=t('reportError');rerenderPage();document.getElementById('report')?.focus();break}c.notes.push(value);c.version++;state.drafts[c.id]='';state.error='';state.notice=t(target.dataset.action==='complete'?'taskCompleted':'reportSaved');if(target.dataset.action==='complete')c.status='done';rerenderPage();document.getElementById('report')?.focus();break}
 }
});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.mobileOpen){state.mobileOpen=false;document.querySelector('.sidebar')?.classList.remove('open');const toggle=document.querySelector<HTMLElement>('[data-action="menu"]');toggle?.setAttribute('aria-expanded','false');toggle?.focus()}});
window.addEventListener('hashchange',route);route();
