import {initViewport} from './viewport';
import {initPwa,hosted,standalone,canPrompt,installApp} from '../pwa/client';
import {restore,createSnapshotWriter,storageKey} from './storage';
import {channels,outcomes,emptyReport,validateReport,saveReport,type ReportDraft} from './report';
import {palette, tokens} from '../design/tokens';
import {translate,brand,localeNames,type Locale,type MessageKey} from '../i18n/messages';
import {initialCases,sourceMessage,demoMembers,demoMeta,type CaseRecord,type CaseDue} from './data';
type Page='today'|'cases'|'reviews'|'imports'|'system'|'detail';
const state={locale:'ja' as Locale,page:'today' as Page,caseId:1,cases:structuredClone(initialCases),review:'pending',reviewOwner:demoMembers[0],reviewDue:'dueNow' as 'dueNow'|'futureDate'|'dueUnknown',imported:false,search:'',owner:'',filter:'all',drafts:{} as Record<number,ReportDraft>,statusFilter:'',designView:'colors',error:'',notice:'',mobileOpen:false};
try{const saved=restore(localStorage);if(saved)Object.assign(state,saved)}catch{}
let writeSnapshot:ReturnType<typeof createSnapshotWriter>|null=null;
try{writeSnapshot=createSnapshotWriter(localStorage,state)}catch{}
let storageError:'storageConflict'|'localFailure'|null=null;
initPwa();
initViewport();
const root=document.getElementById('app');if(!root)throw new Error('Missing app root');
const app:HTMLElement=root;
const t=(k:MessageKey,p:Record<string,string|number>={})=>translate(state.locale,k,p);
const esc=(s:string|number)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const paths:Record<string,string>={user:'M8 7a4 4 0 1 0 8 0 4 4 0 0 0-8 0 M4 21v-3a6 6 0 0 1 6-6h4a6 6 0 0 1 6 6v3',calendar:'M4 5h16v16H4Z M8 3v4 M16 3v4 M4 10h16',copy:'M9 9h12v12H9Z M15 9V3H3v12h6',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6',note:'M4 3h16v18H4Z M8 8h8 M8 12h8 M8 16h4',chevron:'m6 9 6 6 6-6',alert:'M12 3 2 21h20Z M12 9v5 M12 17v1',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v5l3 2',check:'m5 12 4 4L19 6',install:'M12 3v12 m-5-5 5 5 5-5 M4 17v4h16v-4',info:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 11v6 M12 7v1',home:'M3 10 12 3l9 7v10H3Z M9 20v-7h6v7',cases:'M3 5h7l2 3h9v12H3Z',reviews:'m5 12 4 4L19 6 M3 3h18v18H3Z',imports:'M12 16V3 m-5 5 5-5 5 5 M3 15v6h18v-6',system:'M4 5h16 M4 12h16 M4 19h16 M8 3v4 M16 10v4 M9 17v4',arrow:'M4 12h16 m-6-6 6 6-6 6',back:'M20 12H4 m6-6-6 6 6 6',close:'m6 6 12 12 M6 18 18 6',menu:'M4 6h16 M4 12h16 M4 18h16'};
const icon=(name:string)=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]??paths.arrow}"></path></svg>`;
const link=(text:MessageKey,href:string)=>`<a class="button" href="${href}">${t(text)}${icon('arrow')}</a>`;
const button=(text:MessageKey,action:string,variant='')=>`<button class="button ${variant}" data-action="${action}">${t(text)}</button>`;
const pill=(text:string,variant='')=>`<span class="pill ${variant}">${variant?icon(({error:'alert',warning:'clock',success:'check',info:'info'} as Record<string,string>)[variant]??'info'):''}${esc(text)}</span>`;
const dueLabel=(c:CaseRecord)=>c.level==='overdue'?t('overdueDeadline',{date:t(c.due)}):t(c.due);
const duePill=(c:CaseRecord)=>pill(dueLabel(c),c.level==='overdue'?'error':c.level==='today'?'warning':'');
const ownerName=(c:CaseRecord)=>c.owner||t('unknown');
const iconLink=(key:MessageKey,href:string,name:string)=>`<a class="icon-button tip ${['back','guide','architecture'].includes(key)?'tip-start':''}" href="${href}" aria-label="${t(key)}" data-tooltip="${t(key)}">${icon(name)}</a>`;
const iconAction=(key:MessageKey,action:string,name:string)=>`<button class="icon-button tip ${action==='copy'?'tip-start':''}" data-action="${action}" aria-label="${t(key)}" data-tooltip="${t(key)}">${icon(name)}</button>`;
const fold=(key:MessageKey,body:string,opened=false)=>`<details class="disclosure" ${opened?'open':''}><summary>${t(key)}${icon('chevron')}</summary><div class="disclosure-body">${body}</div></details>`;
const header=(title:MessageKey,action='')=>`<header class="page-head"><h1 id="page-title" tabindex="-1">${t(title)}</h1>${action}</header>`;
const options=(keys:readonly MessageKey[],value:string)=>keys.map(k=>`<option value="${k}" ${value===k?'selected':''}>${t(k)}</option>`).join('');
const draft=()=>state.drafts[state.caseId]??(state.drafts[state.caseId]=emptyReport());
const current=()=>state.cases.find(c=>c.id===state.caseId)??state.cases[0];
function renderShell(){
 document.documentElement.lang=state.locale;document.title=t('app');
 const navs:readonly [Page,MessageKey,string][]=[['today','today','home'],['cases','cases','cases'],['reviews','reviews','reviews'],['imports','imports','imports'],['system','system','system']];
 app.innerHTML=`<a class="button skip" href="#main">${t('skip')}</a><div class="app"><aside class="sidebar ${state.mobileOpen?'open':''}"><div class="sidebar-top"><a class="brand" href="#today" aria-label="${brand}"><svg class="brand-mark" viewBox="0 0 32 32" aria-hidden="true"><path d="M4 23V9h9a6 6 0 0 1 0 12H9 M15 21l7 7 M20 4h8v15"></path></svg></a><button class="icon-button mobile-toggle" data-action="menu" aria-label="${t('menu')}" aria-controls="main-nav" aria-expanded="${state.mobileOpen}">${icon('menu')}</button></div><nav id="main-nav" aria-label="${t('menu')}">${navs.map(([p,k,i])=>`<a class="nav-link tip" href="#${p}" aria-label="${t(k)}" data-tooltip="${t(k)}" ${state.page===p||(p==='cases'&&state.page==='detail')?'aria-current="page"':''}>${icon(i)}<span class="nav-caption">${t(k)}</span>${p==='reviews'&&state.review==='pending'?'<span class="nav-dot" aria-hidden="true"></span>':''}</a>`).join('')}</nav></aside><main id="main" tabindex="-1"><div class="topbar"><span class="meta">${t('previewShort')}</span><div class="top-actions"><label class="sr-only" for="locale">${t('language')}</label><select id="locale" class="locale-select">${(['ja','en'] as const).map(l=>`<option value="${l}" ${state.locale===l?'selected':''}>${localeNames[l]}</option>`).join('')}</select>${standalone()?'':iconAction('installTitle','install-info','install')}${iconAction('previewInfo','preview-info','info')}</div></div><p id="storage-error" class="notice error" role="alert" ${storageError?'':'hidden'}>${storageError?t(storageError):''}</p><div id="page">${renderPage()}</div></main></div><dialog id="modal" aria-labelledby="modal-title"><div class="dialog-head"><h2 id="modal-title"></h2>${iconAction('close','close','close')}</div><div id="modal-body" class="dialog-body"></div></dialog><div id="toast" class="toast" role="status" aria-live="polite" hidden></div>`;
}
function task(c:CaseRecord,index:number){return `<article class="task"><span class="task-number">${String(index+1).padStart(2,'0')}</span><div><div class="row space-between"><a class="details-link" href="#case/${c.id}">${esc(c.name)}</a>${duePill(c)}</div><h3 class="task-title">${esc(c.title)}</h3><div class="task-foot"><div class="row"><span class="meta">${esc(ownerName(c))}</span>${pill(t(c.status))}</div>${iconLink('open',`#case/${c.id}`,'arrow')}</div></div></article>`}
function today(){const active=state.cases.filter(c=>c.status!=='done');const due=active.filter(c=>['today','overdue'].includes(c.level)).sort((a,b)=>Number(b.level==='overdue')-Number(a.level==='overdue'));return header('today',iconLink('add','#imports','imports'))+`<section class="metrics" aria-label="${t('today')}">${([['dueToday',due.length],['overdue',active.filter(c=>c.level==='overdue').length],['unassigned',active.filter(c=>!c.owner||c.due==='dueUnknown').length]] as const).map(([k,v])=>`<div class="metric"><p class="metric-label">${t(k)}</p><p class="metric-value">${v}</p></div>`).join('')}</section>${state.review==='pending'?`<a class="review-strip" href="#reviews">${icon('reviews')}<span>${t('reviewPending')}</span><span class="count">1</span>${icon('arrow')}</a>`:''}<section class="reading">${due.length?due.map(task).join(''):`<div class="empty"><h2>${t('emptyToday')}</h2>${iconLink('browse','#cases','cases')}</div>`}</section>`}
function filtered(){return state.cases.filter(c=>(!state.owner||c.owner===state.owner)&&(!state.statusFilter||c.status===state.statusFilter)&&`${c.name} ${c.area} ${c.title}`.toLocaleLowerCase().includes(state.search.toLocaleLowerCase())&&(state.filter==='all'||(state.filter==='unknown'?!c.owner:['today','overdue'].includes(c.level)&&c.status!=='done')))}
function rows(){const data=filtered();return data.length?data.map(c=>`<tr><td><a class="details-link" href="#case/${c.id}">${esc(c.name)}</a><p class="meta">${esc(c.area)}</p></td><td><span class="meta">${t(c.stage)}</span></td><td>${esc(c.title)}<p class="meta">${t(c.status)}</p></td><td>${esc(ownerName(c))}</td><td>${duePill(c)}</td></tr>`).join(''):`<tr><td colspan="5"><div class="empty"><h3>${t('noResults')}</h3><p>${t('noResultsSub')}</p>${iconAction('resetFilters','reset','close')}</div></td></tr>`}
function caseCards(){const data=filtered();return data.length?data.map(c=>`<article class="case-card"><div class="row space-between"><div><a class="details-link" href="#case/${c.id}">${esc(c.name)}</a><p class="meta">${esc(c.area)}</p></div>${duePill(c)}</div><h2 class="case-card-title">${esc(c.title)}</h2><div class="row">${pill(t(c.stage))}${pill(t(c.status),c.status==='done'?'success':'')}</div><div class="task-foot"><span class="row meta">${icon('user')}<span class="sr-only">${t('owner')}</span>${esc(ownerName(c))}</span>${iconLink('open',`#case/${c.id}`,'arrow')}</div></article>`).join(''):`<div class="empty"><h2>${t('noResults')}</h2><p>${t('noResultsSub')}</p>${iconAction('resetFilters','reset','close')}</div>`}
function cases(){return header('casesTitle')+`<div class="toolbar"><div class="search-wrap">${icon('search')}<label class="sr-only" for="search">${t('search')}</label><input class="search" id="search" type="search" value="${esc(state.search)}" placeholder="${t('searchShort')}"></div><label class="sr-only" for="owner">${t('owner')}</label><select id="owner"><option value="">${t('allOwners')}</option>${demoMembers.map(o=>`<option ${state.owner===o?'selected':''}>${esc(o)}</option>`).join('')}</select><label class="sr-only" for="case-filter">${t('filterLabel')}</label><select id="case-filter">${options(['all','needsAttention','unknown'],state.filter)}</select><label class="sr-only" for="status-filter">${t('status')}</label><select id="status-filter"><option value="">${t('allStatuses')}</option>${options(['todo','doing','awaiting','done'],state.statusFilter)}</select>${iconAction('resetFilters','reset','close')}</div><p class="meta result-count" id="result-count" role="status">${t('count',{count:filtered().length})}</p><section class="case-cards" id="case-cards" aria-label="${t('cases')}">${caseCards()}</section><div class="table-region cases-table" tabindex="0" role="region" aria-label="${t('cases')}"><table><thead><tr>${(['name','stage','action','owner','due'] as const).map(k=>`<th scope="col">${t(k)}</th>`).join('')}</tr></thead><tbody id="case-rows">${rows()}</tbody></table></div>`}
const fact=(key:MessageKey,value:string)=>{const symbol=({owner:'user',next:'calendar'} as Partial<Record<MessageKey,string>>)[key];return `<div class="fact"><dt>${symbol?`<span class="fact-icon" title="${t(key)}">${icon(symbol)}<span class="sr-only">${t(key)}</span></span>`:t(key)}</dt><dd>${esc(value)}</dd></div>`};
function reportForm(){const d=draft();const required=d.channel==='channelOther'||d.outcome==='resultOther';const invalid=state.error?validateReport(d):null;const field=(id:string,label:MessageKey,content:string)=>`<div class="field"><label for="${id}">${t(label)}</label><select id="${id}" aria-invalid="${invalid?.field===id}" ${invalid?.field===id?'aria-describedby="report-error"':''}>${content}</select></div>`;
 return `<section class="panel"><h2>${t('activity')}</h2><div class="stack block-gap">${field('report-channel','recordMethod',`<option value="">${t('choose')}</option>${options(channels,d.channel)}`)}${field('report-outcome','recordOutcome',`<option value="">${t('choose')}</option>${options(outcomes,d.outcome)}`)}${field('report-mode','recordMode',`<option value="record" ${d.mode==='record'?'selected':''}>${t('recordOnly')}</option><option value="complete" ${d.mode==='complete'?'selected':''} ${current().status==='done'?'disabled':''}>${t('recordAndComplete')}</option>`)}</div>${fold(required?'noteRequired':'noteOptional',`<label class="sr-only" for="report">${t(required?'noteRequired':'noteOptional')}</label><textarea id="report" aria-invalid="${invalid?.field==='report'}" ${invalid?.field==='report'?'aria-describedby="report-error"':''} placeholder="${t('recordNotePlaceholder')}">${esc(d.note)}</textarea>`,required||Boolean(d.note))}${state.error?`<p id="report-error" class="field-error" role="alert">${esc(state.error)}</p>`:''}<div class="form-actions">${button(d.mode==='complete'?'saveComplete':'saveRecord','save','primary')}</div>${state.notice?`<p class="notice success block-gap" role="status">${icon('check')}${esc(state.notice)}</p>`:''}</section>`}
function details(){const c=current();return `<header class="page-head"><div class="case-heading">${iconLink('back','#cases','back')}<div><h1 id="page-title" tabindex="-1">${esc(c.name)}</h1><p>${esc(c.area)}</p></div></div>${iconAction('handoff','handoff','note')}</header><div class="detail-grid"><section><div class="row">${pill(t(c.stage))}${pill(t(c.status),c.status==='done'?'success':'')}${duePill(c)}</div><h2 class="block-gap">${esc(c.title)}</h2><dl class="fact-grid">${fact('owner',ownerName(c))}${fact('next',c.next)}${c.waiting!=='—'?fact('waiting',c.waiting):''}</dl>${fold('context',`<p>${esc(c.reason)}</p>`)}${fold('timeline',`<ol class="timeline">${c.history.map(([d,b])=>`<li><span class="meta">${esc(d)}</span><p>${esc(b)}</p></li>`).join('')}</ol>`)}${fold('evidence',`<p class="meta">${t('evidenceOrigin')}</p><p class="block-gap">${esc(c.evidence)}</p>`)}${c.notes.length?fold('reports',c.notes.map(n=>`<div class="evidence"><small>${t('reported')}</small><p class="pre">${esc(n)}</p></div>`).join('')):''}</section><aside>${reportForm()}</aside></div>`}
function reviews(){if(state.review!=='pending')return header('reviews')+`<div class="empty"><h2>${t(state.review==='approved'?'reviewComplete':'reviewRejected')}</h2>${iconLink('open','#case/1','arrow')}</div>`;return header('reviews')+`<div class="reading"><div class="row space-between">${pill(t('proposal'),'info')}<span class="meta">${demoMeta.messageTime}</span></div><h2 class="block-gap">${t('proposalHeading')}</h2><div class="diff"><section class="diff-side"><span class="meta">${t('before')}</span><p>${t('beforeText')}</p></section><section class="diff-side after"><span class="meta">${t('after')}</span><p>${t('afterText')}</p></section></div>${fold('evidence',`<p>${esc(sourceMessage)}</p><p class="meta block-gap">${t('evidenceOrigin')}</p>`)}<div class="split block-gap"><div class="field"><label for="review-owner">${t('owner')}</label><select id="review-owner">${demoMembers.map(n=>`<option ${state.reviewOwner===n?'selected':''}>${n}</option>`).join('')}</select></div><div class="field"><label for="review-due">${t('due')}</label><select id="review-due">${options(['dueNow','futureDate','dueUnknown'],state.reviewDue)}</select></div></div><p class="notice warning block-gap">${icon('alert')}${t('reviewCaution')}</p>${state.error?`<p class="notice error block-gap" role="alert">${esc(state.error)}</p>`:''}<div class="form-actions">${button('approve','approve','primary')}${button('reject','reject')}</div></div>`}
function imports(){return header('imports')+`<div class="reading"><div class="field"><label for="import-source">${t('importMethod')}</label><select id="import-source"><option>${t('sampleSource')}</option></select></div><div class="block-gap">${button(state.imported?'sampleShown':'sample','sample','primary')}</div><p class="meta block-gap">${t('importNote')}</p>${state.imported?`<section class="section-gap"><h2>${t('imported')}</h2><dl class="fact-grid">${fact('duplicates',t('two'))}${fact('newMessages',t('one'))}</dl>${fold('file',`<p>${demoMeta.fileName}</p><p>${demoMeta.referenceDate}</p>`)}<div class="block-gap">${link('reviewOpen','#reviews')}</div></section>`:''}</div>`}
function system(){
 const colorLabels={main:'mainColor',sub:'subColor',accent:'accentColor'} as const;
 const size=(key:keyof typeof tokens)=>t('tokenSize',{size:parseFloat(tokens[key])*16});
 const sections:Record<string,string>={
 colors:`<div class="palette-grid">${(['main','sub','accent'] as const).map(role=>`<div><div class="swatch ${role}">${palette[role]}</div><p class="swatch-label">${t(colorLabels[role])}</p></div>`).join('')}</div>${fold('context',`<p>${t('paletteBody')}</p><p>${t('derivedColors')}</p>`)}`,
 type:`<dl class="type-specimen">${([['pageType','type-page','type-page'],['sectionType','type-section','type-section'],['bodyType','type-body',''],['labelType','type-label','meta']] as const).map(([label,key,cls])=>`<div><dt>${t(label)} · ${size(key)}</dt><dd class="${cls}">${t('typeSample')}</dd></div>`).join('')}</dl>`,
 space:`<div class="spacing-specimen">${([['relatedGap','related','gap-related'],['groupGap','group','gap-group'],['sectionGap','section','gap-section']] as const).map(([label,cls,key])=>`<div class="row space-between"><span>${t(label)} · ${size(key)}</span><span class="bar ${cls}" aria-hidden="true"></span></div>`).join('')}</div>${fold('spaceTitle',`<p>${t('shapeSpecs',{media:size('radius-sm'),card:size('radius-card'),panel:size('radius-panel'),action:size('action'),touch:size('touch')})}</p>`)}`,
 stack:([['platform','platformBody'],['sequencing','sequencingBody'],['reusable','reusableBody']] as const).map(([h,b])=>fold(h,`<p>${t(b)}</p>`)).join('')
 };
 return header('designSection')+`<div class="reading"><label class="sr-only" for="design-view">${t('designSection')}</label><select id="design-view">${([['colors','designColors'],['type','designType'],['space','designSpace'],['stack','designStack']] as const).map(([value,key])=>`<option value="${value}" ${state.designView===value?'selected':''}>${t(key)}</option>`).join('')}</select>${sections[state.designView]??sections.colors}<div class="row section-gap">${iconLink('guide','./docs/DESIGN_GUIDELINES.md','note')}${iconLink('architecture','./docs/STACK_DECISION.md','system')}</div></div>`;
}
function renderPage(){return ({today,cases,reviews,imports,system,detail:details}[state.page])()}
function rerenderPage(){const target=document.getElementById('page');if(target)target.innerHTML=renderPage()}
function refreshRows(){const cards=document.getElementById('case-cards');if(cards)cards.innerHTML=caseCards();const target=document.getElementById('case-rows');if(target)target.innerHTML=rows();const count=document.getElementById('result-count');if(count)count.textContent=t('count',{count:filtered().length})}
let toastTimer:number|undefined;
function toast(message:string){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.hidden=false;window.clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>{el.hidden=true},4000)}
let modalReturn:HTMLElement|null=null;
function modal(title:MessageKey,body:string){const el=document.getElementById('modal') as HTMLDialogElement;const opening=!el.open;if(opening)modalReturn=document.activeElement instanceof HTMLElement?document.activeElement:null;document.getElementById('modal-title')!.textContent=t(title);document.getElementById('modal-body')!.innerHTML=body;if(opening){el.showModal();el.addEventListener('close',()=>modalReturn?.focus(),{once:true})}}
function handoffText(){const c=current();return `${c.name}\n${t('stage')}: ${t(c.stage)}\n${t('action')}: ${c.title}\n${t('status')}: ${t(c.status)}\n${t('owner')}: ${ownerName(c)}\n${t('waiting')}: ${c.waiting}\n${t('due')}: ${t(c.due)}\n${t('next')}: ${c.next}\n${t('evidence')}: ${c.evidence}\n${t('reports')}: ${c.notes.at(-1)??t('noReport')}\n\n${t('handoffCaution')}`}
function route(){const hash=location.hash.slice(1);if(hash==='main')return;if(hash.startsWith('case/')){state.page='detail';state.caseId=state.cases.find(c=>c.id===Number(hash.split('/')[1]))?.id??1}else state.page=(['today','cases','reviews','imports','system'].includes(hash)?hash:'today') as Page;state.error='';state.notice='';state.mobileOpen=false;renderShell();document.getElementById('page-title')?.focus({preventScroll:true});window.scrollTo(0,0)}
document.addEventListener('input',e=>{const el=e.target;if(el instanceof HTMLInputElement&&el.id==='search'){state.search=el.value;refreshRows()}if(el instanceof HTMLTextAreaElement&&el.id==='report')draft().note=el.value});
document.addEventListener('change',e=>{const el=e.target;if(!(el instanceof HTMLSelectElement))return;
 if(el.id==='locale'){state.locale=el.value==='en'?'en':'ja';state.error='';state.notice='';renderShell();document.getElementById('locale')?.focus()}
 if(el.id==='review-owner')state.reviewOwner=el.value;
 if(el.id==='review-due'&&['dueNow','futureDate','dueUnknown'].includes(el.value))state.reviewDue=el.value as typeof state.reviewDue;
 if(el.id==='owner'){state.owner=el.value;refreshRows()}
 if(el.id==='case-filter'){state.filter=el.value;refreshRows()}
 if(el.id==='status-filter'){state.statusFilter=el.value;refreshRows()}
 if(el.id==='design-view'){state.designView=el.value;rerenderPage();document.getElementById('design-view')?.focus()}
 if(el.id.startsWith('report-')){const d=draft();if(el.id==='report-channel')d.channel=el.value as ReportDraft['channel'];if(el.id==='report-outcome')d.outcome=el.value as ReportDraft['outcome'];if(el.id==='report-mode')d.mode=el.value==='complete'?'complete':'record';state.error='';state.notice='';rerenderPage();document.getElementById(el.id)?.focus()}
});
document.addEventListener('click',async e=>{const target=e.target instanceof Element?e.target.closest('button'):null;if(!target)return;

 switch(target.dataset.action){
 case'preview-info':modal('previewInfo',`<p>${t('demoNote')}</p><p class="block-gap">${t('previewFooter')}</p><p class="block-gap">${t('asOf')}</p><div class="block-gap">${button('resetDemo','reset-demo')}</div>`);break;
 case'install-info':showInstall();break;
 case'install-app':if(await installApp())toast(t('installAccepted'));else showInstall();break;
 case'reset-demo':if(window.confirm(t('resetConfirm'))){try{resetting=true;localStorage.removeItem(storageKey);location.reload()}catch{resetting=false;toast(t('localFailure'))}}break;
 case'menu':state.mobileOpen=!state.mobileOpen;document.querySelector('.sidebar')?.classList.toggle('open',state.mobileOpen);target.setAttribute('aria-expanded',String(state.mobileOpen));break;
 case'reset':state.search='';state.owner='';state.filter='all';state.statusFilter='';rerenderPage();document.getElementById('search')?.focus();break;
 case'sample':state.imported=true;rerenderPage();document.querySelector<HTMLElement>('[data-action="sample"]')?.focus();break;
 case'close':(document.getElementById('modal') as HTMLDialogElement).close();break;
 case'handoff':modal('handoffHeading',`<p class="pre" id="handoff-text">${esc(handoffText())}</p><div class="block-gap">${iconAction('copy','copy','copy')}</div>`);break;
 case'copy':try{await navigator.clipboard.writeText(handoffText());toast(t('copied'))}catch{toast(t('copyError'))}break;
 case'reject':state.review='rejected';renderShell();document.getElementById('page-title')?.focus();break;
 case'approve':{const c=state.cases.find(c=>c.id===1)!;if(c.version!==1){state.error=t('reviewConflict');rerenderPage();break}const owner=(document.getElementById('review-owner') as HTMLSelectElement).value;const due=(document.getElementById('review-due') as HTMLSelectElement).value as CaseDue;c.owner=owner;c.due=due;c.level=due==='dueNow'?'today':due==='dueUnknown'?'unknown':'upcoming';c.status='todo';c.title=translate('ja','afterText');c.reason=translate('ja','reviewCaution');c.waiting='—';c.evidence=sourceMessage;c.version++;c.history=[...c.history,[demoMeta.messageTime,sourceMessage]];state.review='approved';renderShell();document.getElementById('page-title')?.focus();break}
 case'save':{const c=current();const d=draft();const invalid=validateReport(d);if(invalid){state.error=t(invalid.key);rerenderPage();document.getElementById(invalid.field)?.focus();break}if(!saveReport(c,d,state.locale))break;state.notice=t(d.mode==='complete'?'taskCompleted':'reportSaved');state.drafts[c.id]=emptyReport();state.error='';rerenderPage();document.getElementById('report-channel')?.focus();break}

 }
});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.mobileOpen){state.mobileOpen=false;document.querySelector('.sidebar')?.classList.remove('open');const toggle=document.querySelector<HTMLElement>('[data-action="menu"]');toggle?.setAttribute('aria-expanded','false');toggle?.focus()}});
function showInstall(){modal('installTitle',!hosted()?`<p>${t('installHttps')}</p>`:`<div class="stack"><section><h3>${t('iosLabel')}</h3><p>${t('installIos')}</p></section><section><h3>${t('androidLabel')}</h3><p>${t('installAndroid')}</p></section>${canPrompt()?button('installNow','install-app','primary'):''}</div>`)}
let resetting=false;
function saveDevice(){
 if(resetting)return;
 const result=writeSnapshot?.(state)??'unavailable';
 if(result==='saved')storageError=null;
 if(result==='conflict'||result==='unavailable'){
  state.notice='';
  const notice=document.querySelector<HTMLElement>('.notice.success[role="status"]');if(notice)notice.hidden=true;
  storageError=result==='conflict'?'storageConflict':'localFailure';
 }
 const error=document.getElementById('storage-error');if(error){error.textContent=storageError?t(storageError):'';error.hidden=!storageError}
}
for(const name of ['input','change','click'])document.addEventListener(name,()=>queueMicrotask(saveDevice));
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveDevice()});
window.addEventListener('relay-offline-unavailable',()=>toast(t('offlineUnavailable')));
window.addEventListener('offline',()=>toast(t('offlineStatus')));
window.addEventListener('online',()=>toast(t('onlineStatus')));
window.addEventListener('hashchange',route);route();
