import {languageForm,bindLanguageForm} from '../ui/language';
import {createUiContext,browserLocale,persistLocale,hasLocalePreference,type UiContext} from '../i18n/context';
import {icon,actionClass,actionContent,actionLabel} from '../ui/icons';
import {visibleNavigation,activeNavigation,resolveRoute,type Page} from './navigation';
import {showPricing} from './pricing';
import {showScheduling} from './scheduling';
import {showAccount} from './account';
import {initViewport} from './viewport';
import {initPwa,hosted,standalone,canPrompt,installApp} from '../pwa/client';
import {restore,createSnapshotWriter,storageKey} from './storage';
import {channels,outcomes,emptyReport,validateReport,saveReport,type ReportDraft} from './report';
import {translate,brand,type Locale,type MessageKey} from '../i18n/messages';
import {initialCases,sourceMessage,demoMembers,demoMeta,type CaseRecord,type CaseDue} from './data';
const state={locale:browserLocale() as Locale,page:'today' as Page,caseId:1,cases:structuredClone(initialCases),review:'pending',reviewOwner:demoMembers[0],reviewDue:'dueNow' as 'dueNow'|'futureDate'|'dueUnknown',imported:false,search:'',owner:'',filter:'all',drafts:{} as Record<number,ReportDraft>,statusFilter:'',error:'',notice:''};
try{const saved=restore(localStorage);if(saved)Object.assign(state,saved)}catch{}
if(hasLocalePreference())state.locale=browserLocale();
let writeSnapshot:ReturnType<typeof createSnapshotWriter>|null=null;
try{writeSnapshot=createSnapshotWriter(localStorage,state)}catch{}
let storageError:'storageConflict'|'localFailure'|null=null;
initPwa();
initViewport();
const root=document.getElementById('app');if(!root)throw new Error('Missing app root');
const app:HTMLElement=root;
let ui=createUiContext(state.locale);
const t=(k:MessageKey,p:Record<string,string|number>={})=>ui.t(k,p);
const esc=(s:string|number)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const link=(text:MessageKey,href:string)=>`<a class="button" href="${href}">${t(text)}${icon('arrow')}</a>`;
const button=(text:MessageKey,action:string,variant='')=>`<button class="${actionClass(text)} ${variant}" data-action="${action}" ${actionLabel(ui,text)}>${actionContent(ui,text)}</button>`;
const pill=(text:string,variant='')=>`<span class="pill ${variant}">${variant?icon(({error:'alert',warning:'clock',success:'check',info:'info'} as Record<string,string>)[variant]??'info'):''}${esc(text)}</span>`;
const statusPill=(status:CaseRecord['status'])=>`<span class="pill" title="${t(status)}" aria-label="${t(status)}">${icon(({todo:'todo',doing:'clock',awaiting:'waiting',done:'check'} as const)[status])}<span class="sr-only">${t(status)}</span></span>`;
const dueLabel=(c:CaseRecord)=>c.level==='overdue'?t('overdueDeadline',{date:t(c.due)}):t(c.due);
const duePill=(c:CaseRecord)=>pill(dueLabel(c),c.level==='overdue'?'error':c.level==='today'?'warning':'');
const ownerName=(c:CaseRecord)=>c.owner||t('unknown');
const iconLink=(key:MessageKey,href:string,name:string)=>`<a class="icon-button tip ${key==='back'?'tip-start':''}" href="${href}" aria-label="${t(key)}" data-tooltip="${t(key)}">${icon(name)}</a>`;
const iconAction=(key:MessageKey,action:string,name:string)=>`<button class="icon-button tip ${action==='copy'?'tip-start':''}" data-action="${action}" aria-label="${t(key)}" data-tooltip="${t(key)}">${icon(name)}</button>`;
const fold=(key:MessageKey,body:string,opened=false)=>`<details class="disclosure" ${opened?'open':''}><summary>${t(key)}${icon('chevron')}</summary><div class="disclosure-body">${body}</div></details>`;
const header=(title:MessageKey,action='')=>`<header class="page-head"><h1 id="page-title" tabindex="-1">${t(title)}</h1>${action}</header>`;
const options=(keys:readonly MessageKey[],value:string)=>keys.map(k=>`<option value="${k}" ${value===k?'selected':''}>${t(k)}</option>`).join('');
const draft=()=>state.drafts[state.caseId]??(state.drafts[state.caseId]=emptyReport());
const current=()=>state.cases.find(c=>c.id===state.caseId)??state.cases[0];
function renderShell(){
 document.body.classList.remove('pricing-presenting');
 ui=createUiContext(state.locale);document.documentElement.lang=ui.language;document.documentElement.dir=ui.dir;document.title=t('app');
 const sidebarScroll=document.querySelector('.sidebar')?.scrollTop??0;
 const navs=visibleNavigation(standalone());
 app.innerHTML=`<a class="button skip" href="#main">${t('skip')}</a><div class="app"><aside class="sidebar" aria-label="${t('menu')}"><div class="sidebar-top"><a class="brand" href="#today" aria-label="${brand}"><svg class="brand-mark" viewBox="0 0 32 32" aria-hidden="true"><path d="M4 23V9h9a6 6 0 0 1 0 12H9 M15 21l7 7 M20 4h8v15"></path></svg></a></div><nav id="main-nav" aria-label="${t('menu')}">${navs.map(item=>{const content=`${icon(item.icon)}${item.id==='reviews'&&state.review==='pending'?`<span class="nav-dot" aria-hidden="true"></span><span class="sr-only">${t('reviewPending')}</span>`:''}`;return item.kind==='page'?`<a class="nav-link" href="#${item.id}" aria-label="${t(item.label)}" title="${t(item.label)}" ${activeNavigation(state.page)===item.id?'aria-current="page"':''}>${content}</a>`:`<button type="button" class="nav-link" data-action="${item.id}" data-dialog-key="${item.label}" aria-label="${t(item.label)}" title="${t(item.label)}" aria-haspopup="dialog" aria-controls="modal" aria-expanded="false">${content}</button>`}).join('')}</nav><div class="sidebar-footer"><button type="button" class="nav-link" data-action="language" data-dialog-key="language" aria-label="${t('language')}" title="${t('language')}" aria-haspopup="dialog" aria-controls="modal" aria-expanded="false">${icon('language')}</button></div></aside><main id="main" tabindex="-1"><div class="topbar"><span class="meta">${t('previewShort')}</span>${ui.fallback?`<span class="meta" role="status">${t('languageFallback')}</span>`:''}</div><p id="storage-error" class="notice error" role="alert" ${storageError?'':'hidden'}>${storageError?t(storageError):''}</p><div id="page">${renderPage()}</div></main></div><dialog id="modal" aria-labelledby="modal-title"><div class="dialog-head"><h2 id="modal-title"></h2>${iconAction('close','close','close')}</div><div id="modal-body" class="dialog-body"></div></dialog><div id="toast" class="toast" role="status" aria-live="polite" hidden></div>`;
 const sidebar=document.querySelector('.sidebar');if(sidebar)sidebar.scrollTop=sidebarScroll;
}
function task(c:CaseRecord,index:number){return `<article class="task"><span class="task-number">${ui.number(index+1,{minimumIntegerDigits:2})}</span><div><div class="row space-between"><a class="details-link" href="#case/${c.id}">${esc(c.name)}</a>${duePill(c)}</div><h3 class="task-title">${esc(c.title)}</h3><div class="task-foot"><div class="row"><span class="meta">${esc(ownerName(c))}</span>${statusPill(c.status)}</div>${iconLink('open',`#case/${c.id}`,'arrow')}</div></div></article>`}
function today(view:UiContext){const {t}=view;const active=state.cases.filter(c=>c.status!=='done');const due=active.filter(c=>['today','overdue'].includes(c.level)).sort((a,b)=>Number(b.level==='overdue')-Number(a.level==='overdue'));return header('today')+`<section class="metrics" aria-label="${t('today')}">${([['dueToday',due.length],['overdue',active.filter(c=>c.level==='overdue').length],['unassigned',active.filter(c=>!c.owner||c.due==='dueUnknown').length]] as const).map(([k,v])=>`<div class="metric"><p class="metric-label" title="${t(k)}">${icon(({dueToday:'calendar',overdue:'clock',unassigned:'user'} as const)[k])}<span>${t(k)}</span></p><p class="metric-value">${ui.number(v)}</p></div>`).join('')}</section>${state.review==='pending'?`<a class="review-strip" href="#reviews">${icon('reviews')}<span>${t('reviewPending')}</span><span class="count">1</span>${icon('arrow')}</a>`:''}<section class="reading">${due.length?due.map(task).join(''):`<div class="empty"><h2>${t('emptyToday')}</h2>${iconLink('browse','#cases','cases')}</div>`}</section>`}
function filtered(){return state.cases.filter(c=>(!state.owner||c.owner===state.owner)&&(!state.statusFilter||c.status===state.statusFilter)&&`${c.name} ${c.area} ${c.title}`.toLocaleLowerCase().includes(state.search.toLocaleLowerCase())&&(state.filter==='all'||(state.filter==='unknown'?!c.owner:['today','overdue'].includes(c.level)&&c.status!=='done')))}
function rows(){const data=filtered();return data.length?data.map(c=>`<tr><td><a class="details-link" href="#case/${c.id}">${esc(c.name)}</a><p class="meta">${esc(c.area)}</p></td><td><span class="meta">${t(c.stage)}</span></td><td>${esc(c.title)}${statusPill(c.status)}</td><td>${esc(ownerName(c))}</td><td>${duePill(c)}</td></tr>`).join(''):`<tr><td colspan="5"><div class="empty"><h3>${t('noResults')}</h3><p>${t('noResultsSub')}</p>${iconAction('resetFilters','reset','close')}</div></td></tr>`}
function caseCards(){const data=filtered();return data.length?data.map(c=>`<article class="case-card"><div class="row space-between"><div><a class="details-link" href="#case/${c.id}">${esc(c.name)}</a><p class="meta">${esc(c.area)}</p></div>${duePill(c)}</div><h2 class="case-card-title">${esc(c.title)}</h2><div class="row">${pill(t(c.stage))}${statusPill(c.status)}</div><div class="task-foot"><span class="row meta">${icon('user')}<span class="sr-only">${t('owner')}</span>${esc(ownerName(c))}</span>${iconLink('open',`#case/${c.id}`,'arrow')}</div></article>`).join(''):`<div class="empty"><h2>${t('noResults')}</h2><p>${t('noResultsSub')}</p>${iconAction('resetFilters','reset','close')}</div>`}
function cases(view:UiContext){const {t}=view;return header('casesTitle')+`<div class="toolbar"><div class="search-wrap">${icon('search')}<label class="sr-only" for="search">${t('search')}</label><input class="search" id="search" type="search" list="case-search-options" value="${esc(state.search)}" placeholder="${t('searchShort')}"><datalist id="case-search-options">${[...new Set(state.cases.flatMap(c=>[c.name,c.area,c.title]))].map(value=>`<option value="${esc(value)}"></option>`).join('')}</datalist></div><label class="sr-only" for="owner">${t('owner')}</label><select id="owner"><option value="">${t('allOwners')}</option>${demoMembers.map(o=>`<option ${state.owner===o?'selected':''}>${esc(o)}</option>`).join('')}</select><label class="sr-only" for="case-filter">${t('filterLabel')}</label><select id="case-filter">${options(['all','needsAttention','unknown'],state.filter)}</select><label class="sr-only" for="status-filter">${t('status')}</label><select id="status-filter"><option value="">${t('allStatuses')}</option>${options(['todo','doing','awaiting','done'],state.statusFilter)}</select>${iconAction('resetFilters','reset','close')}</div><p class="meta result-count" id="result-count" role="status">${t('count',{count:filtered().length})}</p><section class="case-cards" id="case-cards" aria-label="${t('cases')}">${caseCards()}</section><div class="table-region cases-table" tabindex="0" role="region" aria-label="${t('cases')}"><table><thead><tr>${(['name','stage','action','owner','due'] as const).map(k=>`<th scope="col">${t(k)}</th>`).join('')}</tr></thead><tbody id="case-rows">${rows()}</tbody></table></div>`}
const fact=(key:MessageKey,value:string)=>{const symbol=({owner:'user',next:'calendar'} as Partial<Record<MessageKey,string>>)[key];return `<div class="fact"><dt>${symbol?`<span class="fact-icon" title="${t(key)}">${icon(symbol)}<span class="sr-only">${t(key)}</span></span>`:t(key)}</dt><dd dir="auto">${esc(value)}</dd></div>`};
function reportForm(){const d=draft();const required=d.channel==='channelOther'||d.outcome==='resultOther';const invalid=state.error?validateReport(d):null;const field=(id:string,label:MessageKey,content:string)=>`<div class="field"><label for="${id}">${t(label)}</label><select id="${id}" aria-invalid="${invalid?.field===id}" ${invalid?.field===id?'aria-describedby="report-error"':''}>${content}</select></div>`;
 return `<section class="panel"><h2>${t('activity')}</h2><div class="stack block-gap">${field('report-channel','recordMethod',`<option value="">${t('choose')}</option>${options(channels,d.channel)}`)}${field('report-outcome','recordOutcome',`<option value="">${t('choose')}</option>${options(outcomes,d.outcome)}`)}${field('report-mode','recordMode',`<option value="record" ${d.mode==='record'?'selected':''}>${t('recordOnly')}</option><option value="complete" ${d.mode==='complete'?'selected':''} ${current().status==='done'?'disabled':''}>${t('recordAndComplete')}</option>`)}</div>${fold(required?'noteRequired':'noteOptional',`<label class="sr-only" for="report">${t(required?'noteRequired':'noteOptional')}</label><textarea id="report" aria-invalid="${invalid?.field==='report'}" ${invalid?.field==='report'?'aria-describedby="report-error"':''} placeholder="${t('recordNotePlaceholder')}">${esc(d.note)}</textarea>`,required||Boolean(d.note))}${state.error?`<p id="report-error" class="field-error" role="alert">${esc(state.error)}</p>`:''}<div class="form-actions">${button(d.mode==='complete'?'saveComplete':'saveRecord','save','primary')}</div>${state.notice?`<p class="notice success block-gap" role="status">${icon('check')}${esc(state.notice)}</p>`:''}</section>`}
function details(view:UiContext){const {t}=view;const c=current();return `<header class="page-head"><div class="case-heading">${iconLink('back','#cases','back')}<div><h1 id="page-title" tabindex="-1">${esc(c.name)}</h1><p>${esc(c.area)}</p></div></div>${iconAction('handoff','handoff','note')}</header><div class="detail-grid"><section><div class="row">${pill(t(c.stage))}${statusPill(c.status)}${duePill(c)}</div><h2 class="block-gap">${esc(c.title)}</h2><dl class="fact-grid">${fact('owner',ownerName(c))}${fact('next',c.next)}${c.waiting!=='—'?fact('waiting',c.waiting):''}</dl>${fold('context',`<p>${esc(c.reason)}</p>`)}${fold('timeline',`<ol class="timeline">${c.history.map(([d,b])=>`<li><span class="meta">${esc(d)}</span><p>${esc(b)}</p></li>`).join('')}</ol>`)}${fold('evidence',`<p class="meta">${t('evidenceOrigin')}</p><p class="block-gap">${esc(c.evidence)}</p>`)}${c.notes.length?fold('reports',c.notes.map(n=>`<div class="evidence"><small>${t('reported')}</small><p class="pre">${esc(n)}</p></div>`).join('')):''}</section><aside>${reportForm()}</aside></div>`}
function reviews(view:UiContext){const {t}=view;if(state.review!=='pending')return header('reviews')+`<div class="empty"><h2>${t(state.review==='approved'?'reviewComplete':'reviewRejected')}</h2>${iconLink('open','#case/1','arrow')}</div>`;return header('reviews')+`<div class="reading"><div class="row space-between">${pill(t('proposal'),'info')}<span class="meta">${demoMeta.messageTime}</span></div><h2 class="block-gap">${t('proposalHeading')}</h2><div class="diff"><section class="diff-side"><span class="meta">${t('before')}</span><p>${t('beforeText')}</p></section><section class="diff-side after"><span class="meta">${t('after')}</span><p>${t('afterText')}</p></section></div>${fold('evidence',`<p>${esc(sourceMessage)}</p><p class="meta block-gap">${t('evidenceOrigin')}</p>`)}<div class="split block-gap"><div class="field"><label for="review-owner">${t('owner')}</label><select id="review-owner">${demoMembers.map(n=>`<option ${state.reviewOwner===n?'selected':''}>${n}</option>`).join('')}</select></div><div class="field"><label for="review-due">${t('due')}</label><select id="review-due">${options(['dueNow','futureDate','dueUnknown'],state.reviewDue)}</select></div></div><p class="notice warning block-gap">${icon('alert')}${t('reviewCaution')}</p>${state.error?`<p class="notice error block-gap" role="alert">${esc(state.error)}</p>`:''}<div class="form-actions">${button('approve','approve','primary')}${button('reject','reject')}</div></div>`}
function imports(view:UiContext){const {t}=view;return header('imports')+`<div class="reading"><div class="row">${icon('imports')}<span>${t('sampleSource')}</span></div><div class="block-gap">${button(state.imported?'sampleShown':'sample','sample','primary')}</div><p class="meta block-gap">${t('importNote')}</p>${state.imported?`<section class="section-gap"><h2>${icon('check')}${t('importSummary')}</h2><dl class="fact-grid">${fact('duplicates',t('two'))}${fact('newMessages',t('one'))}</dl>${fold('file',`<p>${demoMeta.fileName}</p><p>${demoMeta.referenceDate}</p>`)}<div class="block-gap">${link('reviewOpen','#reviews')}</div></section>`:''}</div>`}
function renderPage(){return ({today,cases,reviews,imports,detail:details}[state.page])(ui)}
function rerenderPage(){const target=document.getElementById('page');if(target)target.innerHTML=renderPage()}
function refreshRows(){const cards=document.getElementById('case-cards');if(cards)cards.innerHTML=caseCards();const target=document.getElementById('case-rows');if(target)target.innerHTML=rows();const count=document.getElementById('result-count');if(count)count.textContent=t('count',{count:filtered().length})}
let toastTimer:number|undefined;
function toast(message:string){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.hidden=false;window.clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>{el.hidden=true},4000)}
let modalReturn:HTMLElement|null=null;
function modal(title:MessageKey,body:string){const el=document.getElementById('modal') as HTMLDialogElement;const opening=!el.open;if(opening)modalReturn=document.activeElement instanceof HTMLElement?document.activeElement:null;document.querySelectorAll<HTMLElement>('[data-dialog-key]').forEach(item=>item.setAttribute('aria-expanded',String(item.dataset.dialogKey===title)));document.getElementById('modal-title')!.textContent=t(title);document.getElementById('modal-body')!.innerHTML=body;if(opening){el.showModal();el.addEventListener('close',()=>{document.querySelectorAll('[data-dialog-key]').forEach(item=>item.setAttribute('aria-expanded','false'));if(modalReturn?.isConnected)modalReturn.focus()},{once:true})}}
function handoffText(){const c=current();return t('handoffTemplate',{name:c.name,stage:t(c.stage),action:c.title,status:t(c.status),owner:ownerName(c),waiting:c.waiting,due:t(c.due),next:c.next,evidence:c.evidence,reports:c.notes.at(-1)??t('noReport'),caution:t('handoffCaution')})}
function route(){const next=resolveRoute(location.hash,state.cases.map(c=>c.id));if(!next)return;state.page=next.page;if(next.caseId!==undefined)state.caseId=next.caseId;state.error='';state.notice='';renderShell();document.getElementById('page-title')?.focus({preventScroll:true});window.scrollTo(0,0)}
document.addEventListener('input',e=>{const el=e.target;if(el instanceof HTMLInputElement&&el.id==='search'){state.search=el.value;refreshRows()}if(el instanceof HTMLTextAreaElement&&el.id==='report')draft().note=el.value});
document.addEventListener('change',e=>{const el=e.target;if(!(el instanceof HTMLSelectElement))return;
 if(el.id==='review-owner')state.reviewOwner=el.value;
 if(el.id==='review-due'&&['dueNow','futureDate','dueUnknown'].includes(el.value))state.reviewDue=el.value as typeof state.reviewDue;
 if(el.id==='owner'){state.owner=el.value;refreshRows()}
 if(el.id==='case-filter'){state.filter=el.value;refreshRows()}
 if(el.id==='status-filter'){state.statusFilter=el.value;refreshRows()}
 if(el.id.startsWith('report-')){const d=draft();if(el.id==='report-channel')d.channel=el.value as ReportDraft['channel'];if(el.id==='report-outcome')d.outcome=el.value as ReportDraft['outcome'];if(el.id==='report-mode')d.mode=el.value==='complete'?'complete':'record';state.error='';state.notice='';rerenderPage();document.getElementById(el.id)?.focus()}
});
document.addEventListener('click',async e=>{const target=e.target instanceof Element?e.target.closest('button'):null;if(!target)return;

 switch(target.dataset.action){
 case'language':modal('language',languageForm(ui));bindLanguageForm(ui,locale=>{state.locale=locale;persistLocale(locale);const url=new URL(location.href);url.searchParams.set('lang',locale);try{history.replaceState(null,'',url)}catch{}renderShell();document.querySelector<HTMLElement>('[data-action=language]')?.focus();saveDevice()});break;
 case'pricing':showPricing(ui,state.page==='detail'?current().name:'',modal);break;
 case'scheduling':await showScheduling(ui,state.page==='detail'?current().title:'',modal);break;
 case'account':await showAccount(ui,modal);break;
 case'preview-info':modal('previewInfo',`<p>${t('demoNote')}</p><p class="block-gap">${t('previewFooter')}</p><p class="block-gap">${t('asOf')}</p><p class="block-gap">${t('originalData')}</p><div class="block-gap">${button('resetDemo','reset-demo')}</div>`);break;
 case'install-info':showInstall();break;
 case'install-app':if(await installApp())toast(t('installAccepted'));else showInstall();break;
 case'reset-demo':if(window.confirm(t('resetConfirm'))){try{resetting=true;localStorage.removeItem(storageKey);location.reload()}catch{resetting=false;toast(t('localFailure'))}}break;
 case'reset':state.search='';state.owner='';state.filter='all';state.statusFilter='';rerenderPage();document.getElementById('search')?.focus();break;
 case'sample':state.imported=true;rerenderPage();document.querySelector<HTMLElement>('[data-action="sample"]')?.focus();break;
 case'close':(document.getElementById('modal') as HTMLDialogElement).close();break;
 case'handoff':modal('handoffHeading',`<p class="pre" id="handoff-text">${esc(handoffText())}</p><div class="block-gap">${iconAction('copy','copy','copy')}</div>`);break;
 case'copy':try{await navigator.clipboard.writeText(handoffText());toast(t('copied'))}catch{toast(t('copyError'))}break;
 case'reject':state.review='rejected';renderShell();document.getElementById('page-title')?.focus();break;
 case'approve':{const c=state.cases.find(c=>c.id===1)!;if(c.version!==1){state.error=t('reviewConflict');rerenderPage();break}const owner=(document.getElementById('review-owner') as HTMLSelectElement).value;const due=(document.getElementById('review-due') as HTMLSelectElement).value as CaseDue;c.owner=owner;c.due=due;c.level=due==='dueNow'?'today':due==='dueUnknown'?'unknown':'upcoming';c.status='todo';c.title=translate('ja','afterText');c.reason=translate('ja','reviewCaution');c.waiting='—';c.evidence=sourceMessage;c.version++;c.history=[...c.history,[demoMeta.messageTime,sourceMessage]];state.review='approved';renderShell();document.getElementById('page-title')?.focus();break}
 case'save':{const c=current();const d=draft();const invalid=validateReport(d);if(invalid){state.error=t(invalid.key);rerenderPage();document.getElementById(invalid.field)?.focus();break}if(!saveReport(c,d,state.locale))break;state.notice=t(d.mode==='complete'?'taskCompleted':'reportSaved');state.drafts[c.id]=emptyReport();state.error='';rerenderPage();document.getElementById('report-channel')?.focus();break}

 }
});
function showInstall(){modal('installTitle',!hosted()?`<p>${t('installHttps')}</p>`:`<div class="stack"><section><h3>${t('iosLabel')}</h3><p>${t('installIos')}</p></section><section><h3>${t('androidLabel')}</h3><p>${t('installAndroid')}</p></section>${canPrompt()?button('installNow','install-app','primary'):''}</div>`)}
let resetting=false;
function saveDevice(){
 if(resetting)return;
 const result=writeSnapshot?.(state)??'unavailable';
 if(result==='saved')storageError=null;
 if(result==='conflict'||result==='unavailable'){
  state.notice='';
  const notice=document.querySelector<HTMLElement>('.notice.success[role="status"]');if(notice)notice.hidden=true;
  storageError=result==='conflict'?'storageConflict':'localFailure';
 }
 const error=document.getElementById('storage-error');if(error){error.textContent=storageError?t(storageError):'';error.hidden=!storageError}
}
for(const name of ['input','change','click'])document.addEventListener(name,()=>queueMicrotask(saveDevice));
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveDevice()});
window.addEventListener('relay-offline-unavailable',()=>toast(t('offlineUnavailable')));
window.addEventListener('offline',()=>toast(t('offlineStatus')));
window.addEventListener('online',()=>toast(t('onlineStatus')));
window.addEventListener('hashchange',route);route();

const calendarResult=new URLSearchParams(location.search).get('calendar');
if(calendarResult){history.replaceState(null,'',location.pathname+location.hash);void showScheduling(ui,'',modal,calendarResult==='connected'?'calendarReady':'scheduleReconnect');}
